import { promises as fs } from "node:fs";
import { isValidObjectId } from "mongoose";
import { NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";
import { Asset, PublishingJob, RenderJob, Video } from "@/models";
import { resolveStoragePath } from "@/lib/render-engine";
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { await connectToDatabase(); const video = await Video.findById((await params).id).populate("lessonId", "title").populate("scriptId", "title hook narration callToAction status duration").populate("backgroundMusicAssetId", "filename storagePath mimeType status").lean() as unknown as Record<string, unknown> | null; if (!video) return NextResponse.json({ error: "Video not found" }, { status: 404 }); const renderJob = await RenderJob.findOne({ videoId: video._id }).sort({ createdAt: -1 }).lean(); return NextResponse.json({ ...video, renderJob }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const raw = await request.json(); if (!raw || typeof raw !== "object" || Array.isArray(raw) || Object.keys(raw).some((key) => !["title", "description", "backgroundMusicAssetId"].includes(key))) return NextResponse.json({ error: "Only title, description and background music are editable" }, { status: 400 });
    const update: Record<string, unknown> = {}; if ("title" in raw) { const title = String(raw.title || "").trim().slice(0, 200); if (!title) return NextResponse.json({ error: "Video title is required" }, { status: 400 }); update.title = title; } if ("description" in raw) update.description = String(raw.description || "").trim().slice(0, 5000);
    await connectToDatabase(); if ("backgroundMusicAssetId" in raw) { if (raw.backgroundMusicAssetId === null || raw.backgroundMusicAssetId === "") update.backgroundMusicAssetId = null; else { if (!isValidObjectId(raw.backgroundMusicAssetId) || !await Asset.exists({ _id: raw.backgroundMusicAssetId, type: "music", status: { $in: ["generated", "mock"] }, storagePath: { $exists: true, $ne: "" } })) return NextResponse.json({ error: "Background music asset is not ready" }, { status: 409 }); update.backgroundMusicAssetId = raw.backgroundMusicAssetId; } }
    const video = await Video.findByIdAndUpdate((await params).id, update, { new: true, runValidators: true }).lean(); return video ? NextResponse.json(video) : NextResponse.json({ error: "Video not found" }, { status: 404 });
  } catch { return NextResponse.json({ error: "Unable to update video" }, { status: 400 }); }
}
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { await connectToDatabase(); const id = (await params).id; const video = await Video.findById(id).lean() as unknown as { status: string; outputPath?: string; subtitlePath?: string } | null; if (!video) return NextResponse.json({ error: "Video not found" }, { status: 404 }); if (["rendering", "published"].includes(video.status) || await PublishingJob.exists({ videoId: id, status: { $in: ["queued", "uploading", "published"] } })) return NextResponse.json({ error: "Rendering or published videos cannot be deleted" }, { status: 409 }); for (const value of [video.outputPath, video.subtitlePath]) if (value) await fs.rm(resolveStoragePath(value), { force: true }).catch(() => undefined); await Promise.all([RenderJob.deleteMany({ videoId: id }), PublishingJob.deleteMany({ videoId: id, status: { $nin: ["published", "uploading"] } }), Video.deleteOne({ _id: id })]); return NextResponse.json({ deleted: true }); }
