import { promises as fs } from "node:fs";
import { NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";
import { createSrt } from "@/lib/subtitles";
import { storage } from "@/lib/storage";
import { Scene, Video } from "@/models";

type SubtitleEntry = { sceneId: string; sceneNumber: number; start: number; end: number; text: string };
async function context(id: string) { const video = await Video.findById(id).lean() as unknown as { _id: unknown; scriptId?: unknown; subtitlePath?: string } | null; if (!video) return null; const scenes = video.scriptId ? await Scene.find({ scriptId: video.scriptId }).sort({ sceneNumber: 1 }).lean() : []; return { video, scenes }; }
function entries(scenes: Array<Record<string, unknown>>): SubtitleEntry[] { return scenes.map((scene) => ({ sceneId: String(scene._id), sceneNumber: Number(scene.sceneNumber), start: Number(scene.startTime), end: Number(scene.endTime), text: String(scene.subtitleText || scene.narration || "") })); }
async function persist(id: string, items: SubtitleEntry[]) { const filename = `${id}.srt`; const content = createSrt(items.map((item) => ({ text: item.text, start: item.start, end: item.end }))); await storage.save("subtitles", filename, content); const subtitlePath = `subtitles/${filename}`; await Video.findByIdAndUpdate(id, { subtitlePath }); return { subtitlePath, content, entries: items }; }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { await connectToDatabase(); const id = (await params).id; const data = await context(id); if (!data) return NextResponse.json({ error: "Video not found" }, { status: 404 }); let content = ""; if (data.video.subtitlePath) content = await fs.readFile(storage.getPath("subtitles", data.video.subtitlePath.split("/").at(-1) || ""), "utf8").catch(() => ""); return NextResponse.json({ subtitlePath: data.video.subtitlePath, content, entries: entries(data.scenes as unknown as Array<Record<string, unknown>>) }); }
export async function POST(_: Request, { params }: { params: Promise<{ id: string }> }) { await connectToDatabase(); const id = (await params).id; const data = await context(id); if (!data) return NextResponse.json({ error: "Video not found" }, { status: 404 }); if (!data.scenes.length) return NextResponse.json({ error: "Storyboard is required" }, { status: 409 }); return NextResponse.json(await persist(id, entries(data.scenes as unknown as Array<Record<string, unknown>>)), { status: 201 }); }
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const { entries: input } = await request.json(); if (!Array.isArray(input) || input.length < 1 || input.length > 7) return NextResponse.json({ error: "Subtitle entries must contain 1–7 scenes" }, { status: 400 }); await connectToDatabase(); const id = (await params).id; const data = await context(id); if (!data) return NextResponse.json({ error: "Video not found" }, { status: 404 }); const original = entries(data.scenes as unknown as Array<Record<string, unknown>>); if (original.length !== input.length || original.some((item) => !input.some((candidate: { sceneId?: string }) => candidate.sceneId === item.sceneId))) return NextResponse.json({ error: "Subtitle entries must match every storyboard scene" }, { status: 400 }); const updates = original.map((item) => { const candidate = input.find((value: { sceneId?: string }) => value.sceneId === item.sceneId); const text = typeof candidate?.text === "string" ? candidate.text.trim().slice(0, 1000) : ""; if (!text) throw new Error(`Scene ${item.sceneNumber} subtitle cannot be empty`); return { ...item, text }; }); await Scene.bulkWrite(updates.map((item) => ({ updateOne: { filter: { _id: item.sceneId }, update: { subtitleText: item.text } } }))); return NextResponse.json(await persist(id, updates)); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to save subtitles" }, { status: 400 }); } }
