import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";
import { globalIgnores } from "eslint/config";
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });
const config = [...compat.extends("next/core-web-vitals", "next/typescript")];
const ignores = globalIgnores([".next/**", "node_modules/**", "next-env.d.ts"]);
const eslintConfig = [ignores, ...config];
eslintConfig.push({ rules: { "@next/next/no-html-link-for-pages": "off" } });
export default eslintConfig;
