"use client";
import { use, useEffect, useState } from "react";
type Channel = { _id: string; channelName: string; status: string };
export default function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [privacy, setPrivacy] = useState("private"); const [confirmPublic, setConfirmPublic] = useState(false); const [channels, setChannels] = useState<Channel[]>([]); const [channelId, setChannelId] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [tags, setTags] = useState("");
  useEffect(() => { void fetch("/api/youtube/channels").then((response) => response.json()).then((items) => { setChannels(items); setChannelId(items[0]?._id || ""); }).catch(() => setMessage("Unable to load YouTube channels")); }, []);
  const publish = async () => { setBusy(true); setMessage(""); try { const response = await fetch(`/api/videos/${id}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ channelId: channelId || undefined, title: title || undefined, description: description || undefined, tags: tags.split(",").map((value) => value.trim()).filter(Boolean), privacyStatus: privacy, confirmPublic }) }); const data = await response.json(); setMessage(response.ok ? data.message : data.error); } catch { setMessage("Unable to publish"); } finally { setBusy(false); } };
  return <main className="content"><p className="eyebrow">PUBLISH VIDEO</p><h1>YouTube publishing</h1><p className="muted">Videos must be approved before publishing. Default visibility is private. Mock mode never marks a video as published.</p><section className="panel form" style={{ marginTop: 24 }}><label>Title (optional override)<input maxLength={100} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Use generated title"/></label><label>Description (optional override)<textarea maxLength={5000} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Use generated description"/></label><label>Tags<input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="education, science"/></label><label>Channel<select value={channelId} onChange={(event) => setChannelId(event.target.value)}><option value="">Mock / no connected channel</option>{channels.map((channel) => <option key={channel._id} value={channel._id}>{channel.channelName} · {channel.status}</option>)}</select></label><label>Privacy<select value={privacy} onChange={(event) => { setPrivacy(event.target.value); setConfirmPublic(false); }}><option value="private">private (default)</option><option value="unlisted">unlisted</option><option value="public">public</option></select></label>{privacy === "public" && <label className="check-row"><input type="checkbox" checked={confirmPublic} onChange={(event) => setConfirmPublic(event.target.checked)}/> I explicitly confirm public publishing</label>}<button className="primary" disabled={busy || (privacy === "public" && !confirmPublic)} onClick={() => void publish()}>{busy ? "Publishing..." : "Publish"}</button>{message && <p className={/unable|error|required|configured/i.test(message) ? "error" : "success"}>{message}</p>}</section></main>;
}
