import test from "node:test";
import assert from "node:assert/strict";
import sharp from "sharp";
import { availableImageProviders, createImageProvider, GeminiImageProvider, HuggingFaceImageProvider, ImageProviderError, MockImageProvider, OpenAIImageProvider, providerConfigured, validateGeneratedRaster } from "../lib/ai/image-provider.ts";
import { envImageProvider, IMAGE_MODEL_DEFAULTS, validateImageModel, validateImageProviderId } from "../lib/ai/image-settings.ts";
import { estimateCost } from "../lib/ai/usage-service.ts";

const withEnv = async (patch, fn) => { const before = { ...process.env }; for (const [key,value] of Object.entries(patch)) { if (value === undefined) delete process.env[key]; else process.env[key] = value; } try { await fn(); } finally { for (const key of Object.keys(process.env)) if (!(key in before)) delete process.env[key]; Object.assign(process.env, before); } };
const fixture = () => sharp({ create: { width: 12, height: 18, channels: 3, background: "purple" } }).png().toBuffer();

test("registry exposes all four stable provider IDs and configured flags without secrets", () => { const providers = availableImageProviders(); assert.deepEqual(providers.map(item => item.providerId), ["mock","openai","huggingface","gemini"]); assert.ok(providers.every(item => !Object.keys(item).some(key => /key|token|secret/i.test(key)))); });
test("factory creates every adapter and rejects unsupported providers without fallback", () => { assert.equal(createImageProvider("mock").providerId, "mock"); assert.equal(createImageProvider("openai").providerId, "openai"); assert.equal(createImageProvider("huggingface").providerId, "huggingface"); assert.equal(createImageProvider("gemini").providerId, "gemini"); assert.throws(() => createImageProvider("other"), /INVALID_IMAGE_PROVIDER/); });
test("IMAGE_PROVIDER is the default and AI_IMAGE_PROVIDER remains a lower-priority compatibility alias", () => withEnv({ IMAGE_PROVIDER: "huggingface", AI_IMAGE_PROVIDER: "openai" }, async () => assert.equal(envImageProvider(), "huggingface")));
test("legacy AI_IMAGE_PROVIDER works when IMAGE_PROVIDER is absent", () => withEnv({ IMAGE_PROVIDER: undefined, AI_IMAGE_PROVIDER: "openai" }, async () => assert.equal(envImageProvider(), "openai")));
test("provider and model validation reject malformed persisted values", () => { assert.equal(validateImageProviderId("OpenAI"), "openai"); assert.equal(validateImageModel("org/model-v1"), "org/model-v1"); assert.throws(() => validateImageProviderId("auto")); assert.throws(() => validateImageModel("bad model?")); });
test("Mock returns a normalized, validated marked PNG Buffer", async () => { const result = await new MockImageProvider().generateImage({ prompt: "fractions", dimensions: { width: 120, height: 180 } }); assert.equal(result.status, "mock"); assert.ok(Buffer.isBuffer(result.data)); assert.equal(result.mimeType, "image/png"); assert.equal(result.width, 120); assert.equal(result.height, 180); assert.match(result.hash, /^[a-f0-9]{64}$/); });
test("OpenAI uses its selected model and returns normalized provider metadata", () => withEnv({ OPENAI_API_KEY: "test" }, async () => { const bytes = await fixture(); let sent; const provider = new OpenAIImageProvider("custom-image-model", { transport: async request => { sent = request; return { encoded: bytes.toString("base64"), requestId: "req-1" }; } }); const result = await provider.generateImage({ prompt: "x" }); assert.equal(sent.model, "custom-image-model"); assert.equal(result.providerId, "openai"); assert.equal(result.model, "custom-image-model"); assert.equal(result.requestId, "req-1"); }));
test("OpenAI selected without a key is a configuration error and never falls back", () => withEnv({ OPENAI_API_KEY: undefined }, async () => assert.rejects(new OpenAIImageProvider().generateImage({ prompt: "x" }), error => error.code === "CONFIGURATION_ERROR")));
test("Hugging Face posts to official inference route and validates binary image response", () => withEnv({ HF_TOKEN: "test" }, async () => { const bytes = await fixture(); let url, init; const provider = new HuggingFaceImageProvider("black-forest-labs/FLUX.1-schnell", async (u, i) => { url=u; init=i; return new Response(bytes, { status: 200, headers: { "content-type": "image/png", "x-request-id": "hf-1" } }); }); const result = await provider.generateImage({ prompt: "lesson art" }); assert.match(String(url), /router\.huggingface\.co\/hf-inference\/models/); assert.equal(init.method, "POST"); assert.equal(result.width, 12); assert.equal(result.requestId, "hf-1"); }));
test("Hugging Face rejects binary whose declared MIME does not match bytes", () => withEnv({ HF_TOKEN: "test" }, async () => { const bytes = await fixture(); const provider = new HuggingFaceImageProvider(IMAGE_MODEL_DEFAULTS.huggingface, async () => new Response(bytes, { headers: { "content-type": "image/jpeg" } })); await assert.rejects(provider.generateImage({ prompt: "x" }), error => error.code === "INVALID_IMAGE"); }));
test("Hugging Face selected without HF_TOKEN is a configuration error", () => withEnv({ HF_TOKEN: undefined }, async () => assert.rejects(new HuggingFaceImageProvider().generateImage({ prompt: "x" }), error => error.code === "CONFIGURATION_ERROR")));
test("Gemini appears but selected without server key is a configuration error", () => withEnv({ GEMINI_API_KEY: undefined }, async () => assert.rejects(new GeminiImageProvider().generateImage({ prompt: "x" }), error => error.code === "CONFIGURATION_ERROR")));
test("Gemini image inlineData is normalized and validated when fully configured", () => withEnv({ GEMINI_API_KEY: "test" }, async () => { const bytes = await fixture(); const provider = new GeminiImageProvider("gemini-image-test", async () => new Response(JSON.stringify({ candidates: [{ content: { parts: [{ inlineData: { data: bytes.toString("base64"), mimeType: "image/png" } }] } }] }), { status: 200, headers: { "content-type": "application/json", "x-request-id": "gem-1" } })); const result = await provider.generateImage({ prompt: "x" }); assert.equal(result.providerId, "gemini"); assert.equal(result.width, 12); }));
test("shared raster validation rejects empty, corrupt, oversized, and MIME-mismatched data", async () => { await assert.rejects(validateGeneratedRaster(Buffer.alloc(0)), error => error.code === "INVALID_IMAGE"); await assert.rejects(validateGeneratedRaster(Buffer.from("bad")), error => error.code === "INVALID_IMAGE"); const bytes = await fixture(); await assert.rejects(validateGeneratedRaster(bytes, "image/jpeg"), error => error.code === "INVALID_IMAGE"); await withEnv({ MAX_IMAGE_ASSET_SIZE: "1" }, () => assert.rejects(validateGeneratedRaster(bytes), error => error.code === "INVALID_IMAGE")); });
test("unpriced real image usage remains null while Mock usage costs zero", () => { assert.equal(estimateCost({ provider: "mock", model: "mock-image-v1", operation: "image_generation", imageCount: 1 }), 0); assert.equal(estimateCost({ provider: "huggingface", model: "unknown", operation: "image_generation", imageCount: 1 }), null); });
test("configured flags are provider-specific", () => withEnv({ OPENAI_API_KEY: "x", HF_TOKEN: undefined, GEMINI_API_KEY: undefined }, async () => { assert.equal(providerConfigured("mock"), true); assert.equal(providerConfigured("openai"), true); assert.equal(providerConfigured("huggingface"), false); assert.equal(providerConfigured("gemini"), false); }));
test("normalized result includes dimensions, hash, request ID, and usage", () => withEnv({ OPENAI_API_KEY: "x" }, async () => { const bytes = await fixture(); const result = await new OpenAIImageProvider("m", { transport: async () => ({ encoded: bytes.toString("base64"), requestId: "r" }) }).generateImage({ prompt: "x" }); assert.deepEqual({ width: result.width, height: result.height, requestId: result.requestId, usage: result.usage }, { width: 12, height: 18, requestId: "r", usage: { imageCount: 1 } }); assert.match(result.hash, /^[a-f0-9]{64}$/); }));
test("empty prompts fail before any provider HTTP call", () => withEnv({ HF_TOKEN: "x" }, async () => { let calls=0; const provider = new HuggingFaceImageProvider("m", async () => { calls++; return new Response(); }); await assert.rejects(provider.generateImage({ prompt: "  " }), error => error instanceof ImageProviderError && error.code === "INVALID_REQUEST"); assert.equal(calls, 0); }));
