import test from "node:test";
import assert from "node:assert/strict";
import { OpenAILLMProvider } from "../lib/ai/openai-provider.ts";
import { FallbackAIProvider } from "../lib/ai/fallback-provider.ts";
import { storyboardOutputSchema } from "../lib/ai/storyboard-schema.ts";
import { validateStoryboard } from "../lib/storyboard.ts";
import { contentHash } from "../lib/ai/cache.ts";
import { BudgetExceededError } from "../lib/ai/usage-service.ts";
const analysis = { sourceSummary: "Một phần hai", learningObjectives: ["Hiểu một phần hai"], keyFacts: ["Hai phần bằng nhau"], definitions: [], formulas: [], examples: [], commonMistakes: [], keywords: ["phân số"], difficulty: "beginner" };
async function fixture() { const script = await new FallbackAIProvider().generateScript({ title: "Một phần hai", analysis }); return { script, output: await new FallbackAIProvider().generateStoryboard({ ...script, duration: 30 }) }; }
function response(value, status = 200) { if (status !== 200) return Response.json({ error: { message: "private" } }, { status, headers: { "retry-after": "0" } }); return Response.json({ object: "response", id: "resp_storyboard", model: "gpt-5.6-luna-snapshot", status: "completed", output: [{ type: "message", role: "assistant", content: [{ type: "output_text", text: JSON.stringify(value), annotations: [] }] }], usage: { input_tokens: 321, output_tokens: 654, input_tokens_details: { cached_tokens: 12 } } }); }
async function harness(fn) { const saved = { ...process.env }, original = globalThis.fetch; Object.assign(process.env, { OPENAI_API_KEY: "test-key", AI_LLM_PROVIDER: "openai", MOCK_AI: "false", OPENAI_STORYBOARD_MODEL: "gpt-5.6-luna", AI_RETRY_LIMIT: "2", AI_RETRY_BASE_MS: "0" }); try { await fn(); } finally { globalThis.fetch = original; for (const key of Object.keys(process.env)) if (!(key in saved)) delete process.env[key]; Object.assign(process.env, saved); } }

test("storyboard schema and timeline require Step-10-ready vertical plans", async () => { const { output } = await fixture(); assert.equal(storyboardOutputSchema.safeParse(output).success, true); assert.equal(validateStoryboard(output.scenes, 30).valid, true); for (const changed of [{ ...output, aspectRatio: "16:9" }, { ...output, fps: 24 }, { ...output, scenes: output.scenes.map((s, i) => i ? s : { ...s, order: 2 }) }, { ...output, scenes: output.scenes.map((s, i) => i === 1 ? { ...s, startTime: 2 } : s) }, { ...output, scenes: output.scenes.map((s, i) => i ? s : { ...s, assetRequirements: [] }) }]) assert.equal(storyboardOutputSchema.safeParse(changed).success && validateStoryboard(changed.scenes, 30).valid, false); });

test("storyboard uses Responses Structured Outputs and captures usage", () => harness(async () => { const { script, output } = await fixture(); let request; const attempts = []; globalThis.fetch = async (_url, init) => { request = JSON.parse(init.body); return response(output); }; const actual = await new OpenAILLMProvider().generateStoryboard({ ...script, duration: 30 }, { onAttempt: async value => attempts.push(value) }); assert.equal(storyboardOutputSchema.safeParse(actual).success, true); assert.equal(request.text.format.type, "json_schema"); assert.equal(request.text.format.strict, true); assert.equal(request.store, false); assert.equal(attempts[0].inputTokens, 321); assert.equal(attempts[0].outputTokens, 654); }));

test("storyboard retries invalid/provider failures and budget blocks before OpenAI", () => harness(async () => { const { script, output } = await fixture(); let calls = 0; globalThis.fetch = async () => { calls++; return response({ wrong: true }); }; await assert.rejects(new OpenAILLMProvider().generateStoryboard({ ...script, duration: 30 }), error => error.code === "AI_INVALID_OUTPUT"); assert.equal(calls, 3); calls = 0; globalThis.fetch = async () => { calls++; return response(output); }; await assert.rejects(new OpenAILLMProvider().generateStoryboard({ ...script, duration: 30 }, { beforeAttempt: async () => { throw new BudgetExceededError("blocked"); } }), /blocked/); assert.equal(calls, 0); }));

test("storyboard cache varies by provider/model/prompt/schema/script/duration/visuals/instruction", () => { const base = { provider: "openai", model: "gpt-5.6-luna", promptVersion: "storyboard-generation-v1", schemaVersion: "storyboard-schema-v1", scriptHash: "a", targetDuration: 30, visualSettings: { aspectRatio: "9:16", fps: 30 }, instruction: "" }; const key = contentHash(base); for (const changed of [{ ...base, model: "other" }, { ...base, scriptHash: "b" }, { ...base, targetDuration: 29 }, { ...base, visualSettings: { aspectRatio: "9:16", fps: 60 } }, { ...base, instruction: "nhanh hơn" }]) assert.notEqual(contentHash(changed), key); });
