"use client";
import { useEffect, useState } from "react";
type Snapshot = { _id: string; videoId?: { title?: string }; views: number; likes: number; comments: number; fetchedAt: string };
type Summary = { videos: Record<string, number>; renders: Record<string, number>; publishing: Record<string, number> };
const total = (values: Record<string, number>) => Object.values(values).reduce((sum, value) => sum + value, 0);
export default function Page() {
  const [snapshots, setSnapshots] = useState<Snapshot[]>([]); const [summary, setSummary] = useState<Summary>({ videos: {}, renders: {}, publishing: {} }); const [mode, setMode] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { const response = await fetch("/api/analytics"); const body = await response.json(); if (response.ok) { setSnapshots(body.snapshots || []); setSummary(body.summary || { videos: {}, renders: {}, publishing: {} }); setMode(body.mode); } else setMessage(body.error); };
  useEffect(() => { void load(); }, []);
  const sync = async () => { const response = await fetch("/api/analytics", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); const body = await response.json(); setMessage(response.ok ? body.message || `Synced ${body.synced}` : body.error); if (response.ok && body.mode === "real") await load(); };
  return <main className="content"><p className="eyebrow">OPERATIONS & YOUTUBE</p><h1>Analytics</h1><p className="muted">Live MongoDB totals. YouTube mode: <span className="badge">{mode || "loading"}</span>. Mock previews are never persisted with real analytics.</p><div className="stats" style={{ marginTop: 24 }}><article className="stat"><span>Videos</span><strong>{total(summary.videos)}</strong><small>{summary.videos.approved || 0} approved · {summary.videos.published || 0} published</small></article><article className="stat"><span>Render jobs</span><strong>{total(summary.renders)}</strong><small>{summary.renders.completed || 0} completed · {summary.renders.failed || 0} failed</small></article><article className="stat"><span>Publishing jobs</span><strong>{total(summary.publishing)}</strong><small>{summary.publishing.published || 0} published · {summary.publishing.failed || 0} failed</small></article></div><button className="primary" onClick={() => void sync()}>Sync YouTube analytics</button>{message && <p className="muted">{message}</p>}<section className="panel table-panel" style={{ marginTop: 20 }}><table><thead><tr><th>Video</th><th>Views</th><th>Likes</th><th>Comments</th><th>Fetched</th></tr></thead><tbody>{snapshots.length ? snapshots.map((item) => <tr key={item._id}><td>{item.videoId?.title || "Video"}</td><td>{item.views}</td><td>{item.likes}</td><td>{item.comments}</td><td>{new Date(item.fetchedAt).toLocaleString()}</td></tr>) : <tr><td colSpan={5}>No real YouTube analytics snapshots.</td></tr>}</tbody></table></section></main>;
}
