import { FilterQuery, Types } from "mongoose";
import { connectToDatabase } from "@/lib/mongodb";
import { Grade, modelsByResource, Subject, Textbook } from "@/models";
import type { Resource } from "@/lib/content";
const pageSize = 20;
const escapeRegex = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const populateFor = (resource: Resource) => resource === "textbooks" ? "subjectId gradeId" : resource === "lessons" ? "subjectId gradeId textbookId sourceDocumentIds" : resource === "source-documents" ? "lessonId" : "";
export async function listContent(resource: Resource, params: { page?: number; search?: string; status?: string; subjectId?: string; gradeId?: string; textbookId?: string; lessonId?: string }) {
  await connectToDatabase(); const Model = modelsByResource[resource]; const page = Number.isFinite(params.page) ? Math.max(1, Math.floor(params.page || 1)) : 1; const query: FilterQuery<unknown> = {};
  if (params.search) { const search = escapeRegex(params.search.slice(0, 200)); query.$or = [{ name: { $regex: search, $options: "i" } }, { title: { $regex: search, $options: "i" } }, { originalName: { $regex: search, $options: "i" } }]; }
  if (params.status) query.status = params.status;
  for (const field of ["subjectId", "gradeId", "textbookId", "lessonId"] as const) if (params[field] && Types.ObjectId.isValid(params[field])) query[field] = params[field];
  let itemsQuery = Model.find(query).sort({ order: 1, createdAt: -1 }).skip((page - 1) * pageSize).limit(pageSize);
  const populate = populateFor(resource); if (populate) itemsQuery = itemsQuery.populate(populate);
  const [items, total] = await Promise.all([itemsQuery.lean(), Model.countDocuments(query)]);
  return { items, pagination: { page, pageSize, total, pages: Math.ceil(total / pageSize) } };
}
export async function getContent(resource: Resource, id: string) { await connectToDatabase(); if (!Types.ObjectId.isValid(id)) return null; let query = modelsByResource[resource].findById(id); const populate = populateFor(resource); if (populate) query = query.populate(populate); return query.lean(); }
async function assertReferences(resource: Resource, data: Record<string, unknown>) { if (resource !== "textbooks" && resource !== "lessons") return; const [subject, grade] = await Promise.all([data.subjectId ? Subject.exists({ _id: data.subjectId }) : true, data.gradeId ? Grade.exists({ _id: data.gradeId }) : true]); if (!subject) throw new Error("Subject not found"); if (!grade) throw new Error("Grade not found"); if (resource === "lessons" && data.textbookId) { const book = await Textbook.findById(data.textbookId).select("subjectId gradeId").lean() as unknown as { subjectId: unknown; gradeId: unknown } | null; if (!book) throw new Error("Textbook not found"); if (data.subjectId && String(book.subjectId) !== String(data.subjectId)) throw new Error("Lesson subject must match textbook subject"); if (data.gradeId && String(book.gradeId) !== String(data.gradeId)) throw new Error("Lesson grade must match textbook grade"); } }
export async function createContent(resource: Resource, data: Record<string, unknown>) { await connectToDatabase(); await assertReferences(resource, data); return modelsByResource[resource].create(data); }
export async function updateContent(resource: Resource, id: string, data: Record<string, unknown>) { await connectToDatabase(); if (!Types.ObjectId.isValid(id)) return null; if (resource === "textbooks" || resource === "lessons") { const current = await modelsByResource[resource].findById(id).lean() as unknown as Record<string, unknown> | null; if (!current) return null; await assertReferences(resource, { ...current, ...data }); } return modelsByResource[resource].findByIdAndUpdate(id, data, { new: true, runValidators: true }).lean(); }
export async function deleteContent(resource: Resource, id: string) { await connectToDatabase(); if (!Types.ObjectId.isValid(id)) return null; const objectId = new Types.ObjectId(id); if (resource === "subjects" && await modelsByResource.textbooks.exists({ subjectId: objectId })) throw new Error("Subject is referenced by textbooks"); if (resource === "grades" && await modelsByResource.textbooks.exists({ gradeId: objectId })) throw new Error("Grade is referenced by textbooks"); if (resource === "textbooks" && await modelsByResource.lessons.exists({ textbookId: objectId })) throw new Error("Textbook is referenced by lessons"); if (resource === "lessons" && await modelsByResource["source-documents"].exists({ lessonId: objectId })) throw new Error("Lesson has source documents"); return modelsByResource[resource].findByIdAndDelete(id).lean(); }
