"use client";
import { useEffect, useState } from "react";
type Settings = { values: { render: { width: number; height: number; fps: number; subtitleMargin: number }; youtube: { privacyStatus: string } }; providers: Record<string, { provider: string; model?: string; voice?: string; configured: boolean }>; storage: { root: string }; pricing: { configured: boolean }; budgets: { daily: number; monthly: number } };
type ImageProvider = { providerId: string; displayName: string; defaultModel: string; configured: boolean };
type AISettings = { image: { provider: string; model: string; configured: boolean }; availableProviders: ImageProvider[] };
export default function Page() {
  const [settings, setSettings] = useState<Settings | null>(null), [ai, setAI] = useState<AISettings | null>(null), [message, setMessage] = useState("");
  const load = async () => { const [settingsResponse, aiResponse] = await Promise.all([fetch("/api/settings", { cache: "no-store" }), fetch("/api/settings/ai", { cache: "no-store" })]); const [body, aiBody] = await Promise.all([settingsResponse.json(), aiResponse.json()]); if (settingsResponse.ok && aiResponse.ok) { setSettings(body); setAI(aiBody); } else setMessage(body.error || aiBody.error || "Unable to load settings"); };
  useEffect(() => { void load(); }, []);
  const save = async () => { if (!settings) return; const response = await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...settings.values, confirmPublic: settings.values.youtube.privacyStatus === "public" }) }); const body = await response.json(); setMessage(response.ok ? "Settings saved to MongoDB." : body.error); };
  const saveAI = async () => { if (!ai) return; const response = await fetch("/api/settings/ai", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider: ai.image.provider, model: ai.image.model }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error); setMessage("Image provider saved to MongoDB and reloaded from the server."); await load(); };
  if (!settings || !ai) return <main className="content"><p className="muted">{message || "Loading settings..."}</p></main>;
  const selected = ai.availableProviders.find(item => item.providerId === ai.image.provider);
  return <main className="content"><p className="eyebrow">SYSTEM</p><h1>Settings</h1><p className="muted">Secrets remain protected server environment values. Provider and model selections persist in MongoDB.</p>{message && <p className={message.includes("saved") || message.includes("reloaded") ? "success" : "error"}>{message}</p>}
    <section className="panel form" style={{ marginTop: 24 }} data-testid="image-provider-settings"><p className="eyebrow">AI PROVIDERS</p><h2>Image Generation</h2><label>Provider<select data-testid="image-provider-select" value={ai.image.provider} onChange={event => { const provider = ai.availableProviders.find(item => item.providerId === event.target.value)!; setAI({ ...ai, image: { provider: provider.providerId, model: provider.defaultModel, configured: provider.configured } }); }}><option value="mock">Mock (local)</option><option value="huggingface">Hugging Face</option><option value="openai">OpenAI</option><option value="gemini">Google Gemini</option></select></label><label>Model<input data-testid="image-model-input" value={ai.image.model} onChange={event => setAI({ ...ai, image: { ...ai.image, model: event.target.value } })}/></label><p data-testid="image-provider-configured" className={selected?.configured ? "success" : "error"}>{selected?.configured ? `${selected.displayName} is configured.` : `${selected?.displayName || ai.image.provider} is NOT CONFIGURED. Save is allowed, but generation will return CONFIGURATION_ERROR until its server credential is configured.`}</p><button className="primary" data-testid="save-image-provider" onClick={() => void saveAI()}>Save image provider</button></section>
    <div className="grid" style={{ marginTop: 24 }}><section className="panel"><h2>Provider status</h2>{Object.entries(settings.providers).map(([name, provider]) => <p key={name}><b>{name.toUpperCase()}</b><br/>{provider.provider}{provider.model ? ` / ${provider.model}` : ""}{provider.voice ? ` / ${provider.voice}` : ""} · <span className="badge">{provider.configured ? (provider.provider === "mock" ? "MOCK" : "configured") : "NOT_CONFIGURED"}</span></p>)}<p><b>Pricing</b><br/>{settings.pricing.configured ? "configured" : "NOT_CONFIGURED"}</p><p><b>Budgets</b><br/>Daily: {settings.budgets.daily || "disabled"} · Monthly: {settings.budgets.monthly || "disabled"}</p><p><b>Storage</b><br/>{settings.storage.root}</p></section><section className="panel form"><h2>Production defaults</h2>{(["width","height","fps","subtitleMargin"] as const).map(key => <label key={key}>{key}<input type="number" min="1" value={settings.values.render[key]} onChange={event => setSettings({ ...settings, values: { ...settings.values, render: { ...settings.values.render, [key]: Number(event.target.value) } } })}/></label>)}<label>YouTube privacy<select value={settings.values.youtube.privacyStatus} onChange={event => setSettings({ ...settings, values: { ...settings.values, youtube: { privacyStatus: event.target.value } } })}><option value="private">private (recommended)</option><option value="unlisted">unlisted</option><option value="public">public — explicit choice</option></select></label><button className="primary" onClick={() => void save()}>Save settings</button></section></div></main>;
}
