"use client";
import { useCallback, useEffect, useState } from "react";
type Lesson = { _id: string; title: string; status: string }; type Batch = { batchId: string; status: string; counts: Record<string, number>; createdAt: string };
export default function Page() {
  const [lessons, setLessons] = useState<Lesson[]>([]); const [batches, setBatches] = useState<Batch[]>([]); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [lessonResponse, batchResponse] = await Promise.all([fetch("/api/content/lessons"), fetch("/api/batch")]); const lessonBody = await lessonResponse.json(); const batchBody = await batchResponse.json(); if (!lessonResponse.ok || !batchResponse.ok) throw new Error(lessonBody.error || batchBody.error); setLessons(lessonBody.items || []); setBatches(batchBody); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Unable to load batches"); } }, []);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (!batches.some((batch) => ["running","paused"].includes(batch.status))) return; const timer = setInterval(() => void load(), 3000); return () => clearInterval(timer); }, [batches, load]);
  const toggle = (id: string) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  const start = async () => { setBusy(true); const response = await fetch("/api/batch", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lessonIds: selected }) }); const data = await response.json(); setMessage(response.ok ? `Queued ${data.total} jobs. Script and video approval gates are enforced.` : data.error); if (response.ok) { setSelected([]); await load(); } setBusy(false); };
  const action = async (batchId: string, name: string) => { const response = await fetch(`/api/batch/${batchId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: name }) }); const body = await response.json(); setMessage(response.ok ? `Batch ${name} accepted.` : body.error); await load(); };
  return <main className="content"><p className="eyebrow">AUTOMATION</p><h1>Batch pipeline</h1><p className="muted">Analyze → Script → wait approval → Storyboard → Assets → TTS → Render → wait video approval → YouTube.</p>{message && <p className={/unable|failed|error|not valid/i.test(message) ? "error" : "success"}>{message}</p>}<div className="grid" style={{ marginTop: 24 }}><section className="panel"><h2>Select lessons</h2>{lessons.length ? lessons.map((lesson) => <label key={lesson._id} className="check-row"><input type="checkbox" checked={selected.includes(lesson._id)} onChange={() => toggle(lesson._id)}/> {lesson.title} <span className="badge">{lesson.status}</span></label>) : <p className="muted">No lessons available.</p>}<button className="primary" disabled={busy || !selected.length} onClick={() => void start()}>Start batch ({selected.length})</button></section><section className="panel"><h2>Recent batches</h2>{batches.length === 0 ? <p className="muted">No batches yet.</p> : batches.map((batch) => <article className="batch-row" key={batch.batchId}><div className="panel-title"><b>{batch.batchId.slice(0, 8)}</b><span className="badge">{batch.status}</span></div><p className="muted">{Object.entries(batch.counts || {}).map(([status, count]) => `${status}: ${count}`).join(" · ") || "Preparing"}</p><div className="button-row">{batch.status === "running" && <button onClick={() => void action(batch.batchId, "pause")}>Pause</button>}{batch.status === "paused" && <button onClick={() => void action(batch.batchId, "resume")}>Resume</button>}{!["cancelled","completed"].includes(batch.status) && <button onClick={() => void action(batch.batchId, "cancel")}>Cancel</button>}<button onClick={() => void action(batch.batchId, "retry_failed")}>Retry failed</button></div></article>)}</section></div></main>;
}
