"use client";
import { useCallback, useEffect, useState } from "react";
import Image from "next/image";
const DEFAULT_STORYBOARD = "6aa53aeb0c3c1db7afee71a6";
type Asset = { _id: string; type: string; name?: string; description?: string; tags?: string[]; filename?: string; storagePath?: string; mimeType?: string; provider: string; model?: string; status: string; prompt?: string; width?: number; height?: number; size?: number; style?: string; characterIdentity?: string };
type Requirement = { requirementId: string; type: string; description: string; role: string; required: boolean; status: string; mappedAssetId?: string; matches?: Array<{ asset: Asset; score: number }> };
type Scene = { _id: string; sceneNumber: number; visualDescription: string; requirements: Requirement[] };
export function AssetLibrary() {
  const [assets, setAssets] = useState<Asset[]>([]), [scenes, setScenes] = useState<Scene[]>([]); const [type, setType] = useState(""), [tags, setTags] = useState(""), [search, setSearch] = useState(""); const [storyboardId, setStoryboardId] = useState(DEFAULT_STORYBOARD); const [provider, setProvider] = useState<{ mode: string; message: string }>(); const [message, setMessage] = useState(""), [loading, setLoading] = useState(true), [busy, setBusy] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams(); if (type) params.set("type", type); if (tags) params.set("tags", tags); if (search) params.set("search", search); const [library, board] = await Promise.all([fetch("/api/assets?" + params), fetch(`/api/storyboards/${storyboardId}/assets`)]); const libraryBody = await library.json(); const boardBody = await board.json(); if (!library.ok) throw new Error(libraryBody.error); if (!board.ok) throw new Error(boardBody.error); setAssets(libraryBody.items); setScenes(boardBody.scenes); setProvider(boardBody.provider); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Unable to load assets"); } finally { setLoading(false); } }, [search, storyboardId, tags, type]); useEffect(() => { const id = setTimeout(() => void load(), 200); return () => clearTimeout(id); }, [load]);
  const request = async (key: string, url: string, options: RequestInit) => { setBusy(key); setMessage(""); try { const response = await fetch(url, options); const body = await response.json(); if (!response.ok) { const actions: Record<string, string> = { CONFIGURATION_ERROR: "Configure the selected provider credential on the server, or select Mock in Settings.", AUTHENTICATION_ERROR: "Check the selected provider credential and model permissions.", QUOTA_EXCEEDED: "Check provider billing and quota limits.", RATE_LIMITED: "Wait briefly, then retry.", BUDGET_EXCEEDED: "Increase the configured AI budget or wait for the budget window to reset.", INVALID_REQUEST: "Check the selected model and image prompt/settings.", PROVIDER_ERROR: "The provider is unavailable; retry later or select another configured provider.", INVALID_IMAGE: "The provider returned invalid image bytes; retry or select another provider.", NETWORK_ERROR: "Check server network access to the selected provider." }; throw new Error(`${body.error}${actions[body.code] ? ` ${actions[body.code]}` : ""}`); } setMessage(body.cacheHit ? "CACHE HIT — reused without provider call." : body.reused ? "Existing asset reused." : "Saved."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Operation failed"); } finally { setBusy(""); } };
  const upload = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; await request("upload", "/api/assets", { method: "POST", body: new FormData(form) }); form.reset(); };
  const edit = async (asset: Asset) => { const name = window.prompt("Asset name", asset.name || asset.filename || ""); if (name === null) return; const description = window.prompt("Description", asset.description || ""); if (description === null) return; const tagsValue = window.prompt("Tags (comma separated)", asset.tags?.join(", ") || ""); if (tagsValue === null) return; await request(asset._id, `/api/assets/${asset._id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, description, tags: tagsValue }) }); };
  const match = async () => { setBusy("match"); try { const response = await fetch(`/api/storyboards/${storyboardId}/assets/match`, { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setScenes(body.scenes); setMessage("Ranked reusable matches loaded."); } catch (error) { setMessage(error instanceof Error ? error.message : "Matching failed"); } finally { setBusy(""); } };
  const assign = (scene: Scene, req: Requirement, asset: Asset) => request(req.requirementId, `/api/scenes/${scene._id}/assets`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ assetId: asset._id, requirementId: req.requirementId, role: req.role }) });
  const unmap = (scene: Scene, req: Requirement) => request(req.requirementId, `/api/scenes/${scene._id}/assets`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ requirementId: req.requirementId }) });
  const generate = (scene: Scene, req: Requirement) => request(req.requirementId, `/api/storyboards/${storyboardId}/assets/generate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sceneId: scene._id, requirementId: req.requirementId }) });
  return <main className="content"><div className="manager-head"><div><p className="eyebrow">10. ASSET LIBRARY</p><h1>Asset Library & Scene Mapping</h1><p className="muted">Reuse-first visual assets. Files stay in controlled local storage; mapping never copies files.</p></div><div className="filters"><input aria-label="Storyboard ID" value={storyboardId} onChange={e => setStoryboardId(e.target.value)}/><input placeholder="Search assets" value={search} onChange={e => setSearch(e.target.value)}/><input placeholder="Filter tags" value={tags} onChange={e => setTags(e.target.value)}/><select value={type} onChange={e => setType(e.target.value)}><option value="">All types</option>{["character","background","object","icon","illustration","diagram","image"].map(value => <option key={value}>{value}</option>)}</select></div></div>
    <p data-testid="image-provider" className={provider?.mode === "not_configured" ? "error" : "muted"}>{provider?.message || "Checking image provider…"}</p>
    <form className="panel form compact-form" onSubmit={upload}><h2>Upload image</h2><input name="name" placeholder="Name" maxLength={160}/><select name="type" required defaultValue="image">{["character","background","object","icon","illustration","diagram","image"].map(value => <option key={value}>{value}</option>)}</select><input name="description" placeholder="Description" maxLength={2000}/><input name="tags" placeholder="Tags, comma separated"/><input name="style" placeholder="Style"/><input name="characterIdentity" placeholder="Character identity"/><input name="characterAppearance" placeholder="Character appearance"/><input name="file" type="file" accept="image/png,image/jpeg,image/webp" required/><button className="primary" disabled={busy === "upload"}>{busy === "upload" ? "Uploading…" : "Upload"}</button></form>{message && <p className={/failed|error|cannot|unable|not configured|not found|credits|quota|spend limit|rate limited|rejected|authentication/i.test(message) ? "error" : "success"}>{message}</p>}
    <section className="panel"><div className="panel-title"><div><h2>Approved storyboard requirements</h2><p className="muted">Status and mappings come only from persisted scene requirements.</p></div><button disabled={Boolean(busy)} onClick={() => void match()}>Find reusable matches</button></div>{scenes.map(scene => <div className="requirement-scene" key={scene._id}><h3>Scene {scene.sceneNumber}</h3><p className="muted">{scene.visualDescription}</p>{scene.requirements.map(req => <div className="requirement-row" key={req.requirementId}><div><b>{req.type} · {req.role}</b> <span className="badge">{req.status}</span><p>{req.description}</p></div><div className="button-row">{req.mappedAssetId && <button disabled={busy === req.requirementId} onClick={() => void unmap(scene, req)}>Remove mapping</button>}{req.matches?.map(item => <button key={item.asset._id} disabled={busy === req.requirementId} onClick={() => void assign(scene, req, item.asset)}>Reuse {item.asset.name || item.asset.filename} ({item.score})</button>)}{!req.mappedAssetId && req.matches && req.matches.length === 0 && <button className="primary" disabled={busy === req.requirementId || provider?.mode === "not_configured"} onClick={() => void generate(scene, req)}>Generate missing image</button>}</div></div>)}</div>)}</section>
    <h2>Library</h2>{loading ? <div className="panel"><p className="muted">Loading assets…</p></div> : assets.length === 0 ? <div className="panel empty"><strong>No assets found</strong></div> : <div className="asset-grid">{assets.map(asset => <article className="panel asset-card" key={asset._id}><div className="asset-preview">{asset.storagePath?.startsWith("images/") ? <Image unoptimized width={asset.width || 1080} height={asset.height || 1920} alt={asset.description || asset.name || "Asset"} src={`/api/media?path=${encodeURIComponent(asset.storagePath)}`}/> : <span>No preview</span>}</div><h3>{asset.name || asset.filename || "Generated asset"}</h3><p>{asset.description}</p><p className="muted">{asset.type} · {asset.provider}/{asset.model || "local"} · {asset.width || "?"}×{asset.height || "?"}</p><div className="chips">{asset.tags?.map(tag => <span key={tag}>{tag}</span>)}</div><span className="badge">{asset.status}</span><div className="button-row"><button onClick={() => void edit(asset)}>Rename / metadata</button><button className="delete" disabled={busy === asset._id} onClick={() => void request(asset._id, `/api/assets/${asset._id}`, { method: "DELETE" })}>Delete</button></div></article>)}</div>}
  </main>;
}
