"use client";
import { useCallback, useEffect, useState } from "react";
type Asset = { _id: string; type: string; filename?: string; status: string };
type Scene = { _id: string; sceneNumber: number; assetIds?: Asset[] };
export function AudioMixControls({ videoId }: { videoId: string }) {
  const [assets, setAssets] = useState<Asset[]>([]); const [scenes, setScenes] = useState<Scene[]>([]); const [musicId, setMusicId] = useState(""); const [sfx, setSfx] = useState<Record<string, string>>({}); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const videoResponse = await fetch(`/api/videos/${videoId}`); if (!videoResponse.ok) return; const video = await videoResponse.json(); const [assetResponse, sceneResponse] = await Promise.all([fetch("/api/assets"), video.scriptId?._id ? fetch(`/api/scripts/${video.scriptId._id}/scenes`) : null]); if (assetResponse.ok) setAssets((await assetResponse.json()).items); if (sceneResponse?.ok) setScenes(await sceneResponse.json()); setMusicId(video.backgroundMusicAssetId?._id || ""); }, [videoId]);
  useEffect(() => { void load(); }, [load]);
  const saveMusic = async () => { const response = await fetch(`/api/videos/${videoId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ backgroundMusicAssetId: musicId || null }) }); const body = await response.json(); setMessage(response.ok ? "Background music saved. It will be mixed at 12% with fade and limiter." : body.error); };
  const saveSfx = async (sceneId: string) => { const assetId = sfx[sceneId]; if (!assetId) return; const response = await fetch(`/api/scenes/${sceneId}/assets`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ assetId }) }); const body = await response.json(); setMessage(response.ok ? "Scene SFX saved. It will be mixed at 25% with a limiter." : body.error); if (response.ok) await load(); };
  const music = assets.filter((asset) => asset.type === "music"); const effects = assets.filter((asset) => asset.type === "sfx");
  return <main className="content audio-mix-page"><section className="panel"><h2>Audio mix</h2><p className="muted">Voice remains primary. Optional music and SFX are attenuated and limited by FFmpeg to reduce clipping.</p>{message && <p className={/saved/i.test(message) ? "success" : "error"}>{message}</p>}<div className="form compact-form"><label>Background music<select value={musicId} onChange={(event) => setMusicId(event.target.value)}><option value="">No music</option>{music.map((asset) => <option value={asset._id} key={asset._id}>{asset.filename || asset._id}</option>)}</select></label><button onClick={() => void saveMusic()}>Save music</button></div>{scenes.map((scene) => { const current = scene.assetIds?.find((asset) => asset.type === "sfx"); return <div className="button-row" key={scene._id} style={{ marginTop: 10 }}><b>Scene {scene.sceneNumber}</b><select aria-label={`SFX for scene ${scene.sceneNumber}`} value={sfx[scene._id] || current?._id || ""} onChange={(event) => setSfx({ ...sfx, [scene._id]: event.target.value })}><option value="">No SFX</option>{effects.map((asset) => <option value={asset._id} key={asset._id}>{asset.filename || asset._id}</option>)}</select><button disabled={!sfx[scene._id]} onClick={() => void saveSfx(scene._id)}>Assign SFX</button></div>; })}{!music.length && !effects.length && <p className="muted">Upload music or SFX in Asset Library to enable mixing.</p>}</section></main>;
}
