"use client";
import { useCallback, useEffect, useState } from "react";

type Kind = "characters" | "styles";
type Item = { _id: string; name: string; description?: string; appearance?: string; personality?: string; visualStyle?: string; visualPromptPrefix?: string; negativePrompt?: string; aspectRatio?: string; typography?: string; subtitleStyle?: string; status: string; tags?: string[] };
const blank = { name: "", description: "", appearance: "", personality: "", visualStyle: "", visualPromptPrefix: "", negativePrompt: "", aspectRatio: "9:16", typography: "", subtitleStyle: "", status: "active", tags: "" };
export function ProfileLibrary({ kind }: { kind: Kind }) {
  const character = kind === "characters"; const [items, setItems] = useState<Item[]>([]); const [form, setForm] = useState({ ...blank }); const [editingId, setEditingId] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [search, setSearch] = useState("");
  const load = useCallback(async () => { try { const query = character && search ? `?search=${encodeURIComponent(search)}` : ""; const response = await fetch(`/api/${kind}${query}`); const body = await response.json(); if (!response.ok) throw new Error(body.error); setItems(body); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load library"); } }, [character, kind, search]);
  useEffect(() => { void load(); }, [load]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { const response = await fetch(`/api/${kind}${editingId ? `/${editingId}` : ""}`, { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setMessage(editingId ? "Saved changes." : `${character ? "Character" : "Style"} created.`); setEditingId(""); setForm({ ...blank }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Save failed"); } finally { setBusy(false); } };
  const edit = (item: Item) => { setEditingId(item._id); setForm({ ...blank, ...item, tags: item.tags?.join(", ") || "" }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = async (item: Item) => { if (!window.confirm(`Delete ${item.name}?`)) return; const response = await fetch(`/api/${kind}/${item._id}`, { method: "DELETE" }); const body = await response.json(); setMessage(response.ok ? "Deleted." : body.error); if (response.ok) await load(); };
  return <main className="content"><div className="manager-head"><div><p className="eyebrow">VISUAL CONSISTENCY</p><h1>{character ? "Character Profiles" : "Style Presets"}</h1><p className="muted">{character ? "Reuse a consistent character description across scenes and videos." : "Reuse visual, typography and subtitle direction across storyboards."}</p></div>{character && <input aria-label="Search characters" placeholder="Search characters" value={search} onChange={(e) => setSearch(e.target.value)}/>}</div>
    <div className="manager-grid"><form className="panel form" onSubmit={save}><h2>{editingId ? "Edit" : "Create"} {character ? "character" : "style"}</h2><label>Name<input required maxLength={120} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label><label>Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></label>{character ? <><label>Appearance<textarea value={form.appearance} onChange={(e) => setForm({ ...form, appearance: e.target.value })}/></label><label>Personality<input value={form.personality} onChange={(e) => setForm({ ...form, personality: e.target.value })}/></label><label>Visual style<input value={form.visualStyle} onChange={(e) => setForm({ ...form, visualStyle: e.target.value })}/></label><label>Tags<input value={form.tags} onChange={(e) => setForm({ ...form, tags: e.target.value })} placeholder="teacher, friendly"/></label></> : <><label>Prompt prefix<textarea value={form.visualPromptPrefix} onChange={(e) => setForm({ ...form, visualPromptPrefix: e.target.value })}/></label><label>Negative prompt<textarea value={form.negativePrompt} onChange={(e) => setForm({ ...form, negativePrompt: e.target.value })}/></label><label>Aspect ratio<select value={form.aspectRatio} onChange={(e) => setForm({ ...form, aspectRatio: e.target.value })}><option>9:16</option><option>16:9</option><option>1:1</option></select></label><label>Typography<input value={form.typography} onChange={(e) => setForm({ ...form, typography: e.target.value })}/></label><label>Subtitle style<input value={form.subtitleStyle} onChange={(e) => setForm({ ...form, subtitleStyle: e.target.value })}/></label></>}<label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="active">Active</option><option value="archived">Archived</option></select></label><div className="button-row"><button className="primary" disabled={busy}>{busy ? "Saving..." : "Save"}</button>{editingId && <button type="button" onClick={() => { setEditingId(""); setForm({ ...blank }); }}>Cancel</button>}</div></form>
      <section className="panel table-panel"><h2>{character ? "Characters" : "Styles"}</h2>{message && <p className={/fail|unable|used|required|exists/i.test(message) ? "error" : "success"}>{message}</p>}{items.length === 0 ? <div className="empty"><p className="muted">No {character ? "characters" : "styles"} yet.</p></div> : <table><thead><tr><th>Name</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item._id}><td><b>{item.name}</b><small>{item.description || "No description"}</small></td><td>{character ? item.visualStyle || item.appearance || "—" : `${item.aspectRatio || "9:16"} · ${item.visualPromptPrefix || "No prefix"}`}</td><td><span className="badge">{item.status}</span></td><td><div className="button-row"><button onClick={() => edit(item)}>Edit</button><button className="delete" onClick={() => void remove(item)}>Delete</button></div></td></tr>)}</tbody></table>}</section></div>
  </main>;
}
