"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
type Job = { _id: string; videoId?: { _id: string; title: string }; status: string; progress: number; currentStep?: string; error?: string; logs?: string[]; retryCount: number; createdAt: string };
export function RenderQueue() {
  const [jobs, setJobs] = useState<Job[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const response = await fetch("/api/render-jobs"); const body = await response.json(); if (!response.ok) throw new Error(body.error); setJobs(body); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load render jobs"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (!jobs.some((job) => ["queued","processing"].includes(job.status))) return; const timer = setInterval(() => void load(), 2000); return () => clearInterval(timer); }, [jobs, load]);
  const action = async (id: string, name: string) => { const response = await fetch(`/api/render-jobs/${id}/${name}`, { method: "POST" }); const body = await response.json(); if (!response.ok) setError(body.error); await load(); };
  return <main className="content"><p className="eyebrow">WORKER</p><h1>Render Queue</h1><p className="muted">Live MongoDB jobs, progress, retries, cancellation and worker logs.</p>{error && <p className="error">{error}</p>}{loading ? <div className="panel"><p className="muted">Loading jobs...</p></div> : jobs.length === 0 ? <div className="panel empty"><p className="muted">No render jobs yet.</p></div> : <div className="scene-list">{jobs.map((job) => <article className="panel" key={job._id}><div className="panel-title"><div><h2>{job.videoId?.title || "Deleted video"}</h2><p className="muted">{new Date(job.createdAt).toLocaleString()} · retry {job.retryCount}</p></div><span className="badge">{job.status}</span></div><div className="progress"><i style={{ width: `${job.progress}%` }}/></div><p>{job.progress}% · {job.currentStep || "Waiting"}</p>{job.error && <p className="error">{job.error}</p>}<div className="button-row">{job.videoId && <Link href={`/dashboard/videos/${job.videoId._id}`}>Open video</Link>}{["queued","processing"].includes(job.status) && <button onClick={() => void action(job._id, "cancel")}>Cancel</button>}{job.status === "failed" && <button onClick={() => void action(job._id, "retry")}>Retry</button>}</div>{job.logs?.length ? <details><summary>Worker logs</summary><pre>{job.logs.join("\n")}</pre></details> : null}</article>)}</div>}</main>;
}
