"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { storyboardReadiness } from "@/lib/storyboard-readiness";
type Requirement = { type: "image" | "illustration" | "diagram" | "text" | "animation" | "video"; description: string; role: "background" | "subject" | "overlay" | "supporting"; required: boolean };
type Scene = { _id?: string; order: number; sceneNumber?: number; startTime: number; endTime: number; duration: number; narration: string; visualDescription: string; camera: string; transition: string; onScreenText: string; assetRequirements: Requirement[] };
type Board = { _id: string; title: string; duration: number; aspectRatio: "9:16"; fps: 30; scenes: Scene[]; provider: string; model: string; promptVersion: string; schemaVersion: string; status: string; cached?: boolean; usage?: { inputTokens?: number; outputTokens?: number; estimatedCost?: number | null } };
type Provider = { provider: string; model: string; configured: boolean; runtimeVerified: boolean };
export function StoryboardEditor({ scriptId }: { scriptId: string }) {
  const [board, setBoard] = useState<Board | null>(null), [config, setConfig] = useState<Provider | null>(null), [scriptStatus, setScriptStatus] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [instruction, setInstruction] = useState("");
  const load = useCallback(async () => { const [b, c, s] = await Promise.all([fetch(`/api/scripts/${scriptId}/storyboard`), fetch("/api/health/storyboard"), fetch(`/api/scripts/${scriptId}`)]); if (c.ok) setConfig(await c.json()); if (s.ok) setScriptStatus((await s.json()).status || ""); if (b.ok) { const value = await b.json(); setBoard({ ...value, scenes: value.scenes.map((scene: Scene) => ({ ...scene, order: scene.order || scene.sceneNumber })) }); } else if (b.status !== 404) setMessage((await b.json()).error); }, [scriptId]);
  useEffect(() => { void load(); }, [load]);
  const call = async (url: string, options: RequestInit) => { setBusy(true); setMessage(""); try { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (data.scenes) setBoard({ ...data, scenes: data.scenes.map((s: Scene) => ({ ...s, order: s.order || s.sceneNumber })) }); setMessage(data.cached ? "Cache HIT · không gọi OpenAI." : "Đã lưu vào MongoDB."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Thao tác thất bại."); } finally { setBusy(false); } };
  const generate = (force: boolean) => call(`/api/scripts/${scriptId}/storyboard`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ force, instruction: instruction.trim() || undefined }) });
  const updateScene = (index: number, patch: Partial<Scene>) => board && setBoard({ ...board, scenes: board.scenes.map((scene, i) => i === index ? { ...scene, ...patch } : scene) });
  const updateRequirement = (sceneIndex: number, requirementIndex: number, patch: Partial<Requirement>) => board && updateScene(sceneIndex, { assetRequirements: board.scenes[sceneIndex].assetRequirements.map((item, index) => index === requirementIndex ? { ...item, ...patch } : item) });
  const addRequirement = (sceneIndex: number) => board && updateScene(sceneIndex, { assetRequirements: [...board.scenes[sceneIndex].assetRequirements, { type: "illustration", description: "Mô tả asset cần thiết", role: "supporting", required: false }] });
  const removeRequirement = (sceneIndex: number, requirementIndex: number) => board && board.scenes[sceneIndex].assetRequirements.length > 1 && updateScene(sceneIndex, { assetRequirements: board.scenes[sceneIndex].assetRequirements.filter((_, index) => index !== requirementIndex) });
  const save = () => board && call(`/api/scripts/${scriptId}/storyboard/save`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: board.title, duration: board.duration, aspectRatio: board.aspectRatio, fps: board.fps, scenes: board.scenes.map(scene => ({ order: scene.order, startTime: scene.startTime, endTime: scene.endTime, duration: Number((scene.endTime - scene.startTime).toFixed(2)), narration: scene.narration, visualDescription: scene.visualDescription, camera: scene.camera, transition: scene.transition, onScreenText: scene.onScreenText, assetRequirements: scene.assetRequirements })) }) });
  const duration = useMemo(() => board?.scenes.at(-1)?.endTime || 0, [board]);
  const readiness = storyboardReadiness(scriptStatus), ready = readiness.ready;
  return <main className="content"><p className="eyebrow">9. TẠO STORYBOARD</p><div className="panel-title"><div><h1>Storyboard Studio</h1><p data-testid="storyboard-readiness">{readiness.text}</p><p className="muted">Chỉ lập kế hoạch cho Bước 10, chưa tạo asset hoặc Video.</p><p data-testid="storyboard-provider" className="muted">{!config ? "Đang kiểm tra provider..." : !config.configured ? "⚠️ OpenAI chưa được cấu hình" : config.provider === "openai" ? `${config.runtimeVerified ? "✨ OpenAI đã chạy thực tế" : "OpenAI đã cấu hình"} · ${config.model}` : `🧪 Mock · ${config.model}`}</p></div><div className="button-row"><button className="primary" disabled={busy || !ready} onClick={() => void generate(false)}>{board ? "Generate / Cache" : "Generate"}</button><button disabled={busy || !ready || !board} onClick={() => void generate(true)}>Regenerate</button><button disabled={busy || !ready || !board} onClick={() => void save()}>Save edits</button></div></div>
    <section className="panel"><label>Hướng dẫn tạo lại (tùy chọn)<textarea value={instruction} maxLength={1000} onChange={e => setInstruction(e.target.value)} placeholder="Ví dụ: chuyển cảnh nhanh hơn, vẫn giữ nguyên kiến thức"/></label>{message && <p className={/không|thất bại|phải|chưa/i.test(message) ? "error" : "success"}>{message}</p>}</section>
    {board && <><section className="panel"><div className="panel-title"><h2>{board.title}</h2><span className="badge">{board.status}</span></div><p><b>{board.aspectRatio}</b> · <b>{board.fps}fps</b> · {duration}s / mục tiêu {board.duration}s · {board.scenes.length} cảnh</p><p className="muted">{board.provider}/{board.model} · {board.promptVersion} · {board.schemaVersion} · input {board.usage?.inputTokens ?? "—"} / output {board.usage?.outputTokens ?? "—"} tokens</p><div className="button-row"><button disabled={busy} onClick={() => void call(`/api/scripts/${scriptId}/storyboard/approve`, { method: "POST" })}>Approve</button><button disabled={busy} onClick={() => void call(`/api/scripts/${scriptId}/storyboard/reject`, { method: "POST" })}>Reject</button></div></section>
    <div className="scene-list">{board.scenes.map((scene, index) => <article className="panel scene-card" key={scene._id || scene.order}><div className="scene-number">{scene.order}</div><div className="scene-body"><div className="button-row"><label>Bắt đầu<input type="number" step=".1" value={scene.startTime} onChange={e => updateScene(index, { startTime: Number(e.target.value) })}/></label><label>Kết thúc<input type="number" step=".1" value={scene.endTime} onChange={e => updateScene(index, { endTime: Number(e.target.value) })}/></label><span>{scene.duration}s</span></div><label>Narration<textarea value={scene.narration} onChange={e => updateScene(index, { narration: e.target.value })}/></label><label>Kế hoạch hình ảnh<textarea value={scene.visualDescription} onChange={e => updateScene(index, { visualDescription: e.target.value })}/></label><label>Camera<input value={scene.camera} onChange={e => updateScene(index, { camera: e.target.value })}/></label><label>Transition<input value={scene.transition} onChange={e => updateScene(index, { transition: e.target.value })}/></label><label>Chữ trên màn hình<input value={scene.onScreenText} onChange={e => updateScene(index, { onScreenText: e.target.value })}/></label><h3>Asset requirements (chưa tạo)</h3>{scene.assetRequirements.map((asset, assetIndex) => <div key={assetIndex} className="panel"><div className="button-row"><label>Loại<select aria-label={`Loại asset cảnh ${scene.order} mục ${assetIndex + 1}`} value={asset.type} onChange={e => updateRequirement(index, assetIndex, { type: e.target.value as Requirement["type"] })}>{["image","illustration","diagram","text","animation","video"].map(value => <option key={value}>{value}</option>)}</select></label><label>Vai trò<select aria-label={`Vai trò asset cảnh ${scene.order} mục ${assetIndex + 1}`} value={asset.role} onChange={e => updateRequirement(index, assetIndex, { role: e.target.value as Requirement["role"] })}>{["background","subject","overlay","supporting"].map(value => <option key={value}>{value}</option>)}</select></label><label><input aria-label={`Asset bắt buộc cảnh ${scene.order} mục ${assetIndex + 1}`} type="checkbox" checked={asset.required} onChange={e => updateRequirement(index, assetIndex, { required: e.target.checked })}/> Bắt buộc</label><button type="button" disabled={scene.assetRequirements.length <= 1} onClick={() => removeRequirement(index, assetIndex)}>Xóa</button></div><label>Mô tả asset<textarea aria-label={`Mô tả asset cảnh ${scene.order} mục ${assetIndex + 1}`} value={asset.description} onChange={e => updateRequirement(index, assetIndex, { description: e.target.value })}/></label></div>)}<button type="button" disabled={scene.assetRequirements.length >= 8} onClick={() => addRequirement(index)}>Thêm asset requirement</button></div><div className="visual-preview">9:16<br/><small>{scene.startTime}s–{scene.endTime}s</small></div></article>)}</div></>}
  </main>;
}
