"use client";
import { TTSControls } from "@/components/tts-controls";
import Link from "next/link";
import Image from "next/image";
import { useCallback, useEffect, useState } from "react";
type Asset = { metadata?: { duration?: number; sampleRate?: number; voice?: string }; provider?: string; _id: string; type: string; storagePath?: string; status: string };
type Scene = { _id: string; sceneNumber: number; startTime: number; endTime: number; narration: string; visualDescription: string; status: string; assetIds?: Asset[] };
type Video = { _id: string; title: string; scriptId?: { _id: string; title: string; hook: string; narration: string; callToAction: string; status: string }; lessonId?: { _id: string; title: string }; outputPath?: string; subtitlePath?: string; status: string; duration?: number; renderJob?: { _id: string; status: string; progress: number; currentStep?: string; error?: string } };
type SubtitleEntry = { sceneId: string; sceneNumber: number; start: number; end: number; text: string };
export function VideoStudio({ videoId }: { videoId: string }) {
  const [video, setVideo] = useState<Video | null>(null); const [scenes, setScenes] = useState<Scene[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [subtitles, setSubtitles] = useState<SubtitleEntry[]>([]); const [showSubtitles, setShowSubtitles] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch(`/api/videos/${videoId}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setVideo(data); if (data.scriptId?._id) { const [sceneResponse, subtitleResponse] = await Promise.all([fetch(`/api/scripts/${data.scriptId._id}/scenes`), fetch(`/api/videos/${videoId}/subtitles`)]); const sceneBody = await sceneResponse.json(); if (sceneResponse.ok) setScenes(sceneBody); if (subtitleResponse.ok) setSubtitles((await subtitleResponse.json()).entries); } setMessage(""); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Unable to load video"); } }, [videoId]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (!video || !["rendering"].includes(video.status)) return; const timer = setInterval(() => void load(), 2000); return () => clearInterval(timer); }, [load, video]);
  const action = async (path: string) => { setBusy(true); try { const response = await fetch(`/api/videos/${videoId}/${path}`, { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage(path === "render" ? "Render queued." : `Video ${path}d.`); await load(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Action failed"); } finally { setBusy(false); } };
  const saveSubtitles = async (generateOnly = false) => { setBusy(true); try { const response = await fetch(`/api/videos/${videoId}/subtitles`, generateOnly ? { method: "POST" } : { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entries: subtitles }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setMessage(generateOnly ? "Subtitles generated." : "Subtitles saved."); setSubtitles(body.entries); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Subtitle operation failed"); } finally { setBusy(false); } };
  const removeVideo = async () => { if (!video || !window.confirm(`Delete ${video.title}? Render output and subtitles will also be removed.`)) return; setBusy(true); const response = await fetch(`/api/videos/${videoId}`, { method: "DELETE" }); const body = await response.json(); if (response.ok) window.location.assign("/dashboard/videos"); else { setMessage(body.error); setBusy(false); } };
  if (!video) return <main className="content"><p className={message ? "error" : "muted"}>{message || "Loading Video Studio..."}</p></main>;
  return <main className="content studio"><div className="panel-title"><div><p className="eyebrow">VIDEO STUDIO</p><h1>{video.title}</h1><p className="muted">{video.status} · {video.duration || 0}s</p></div><div className="button-row"><button className="primary" disabled={busy || video.status === "rendering"} onClick={() => void action("render")}>{video.status === "rejected" || video.status === "failed" ? "Render again" : "Render video"}</button>{video.outputPath && <a href={`/api/videos/${videoId}/download`}>Download MP4</a>}<Link href="/dashboard/render-queue">Render queue</Link><button className="delete" disabled={busy || ["rendering","published"].includes(video.status)} onClick={() => void removeVideo()}>Delete</button></div></div>{message && <p className={/failed|required|only|error|missing|cannot/i.test(message) ? "error" : "success"}>{message}</p>}{video.renderJob && <section className="panel render-summary"><div className="panel-title"><h2>Latest render</h2><span className="badge">{video.renderJob.status}</span></div><div className="progress"><i style={{ width: `${video.renderJob.progress}%` }}/></div><p>{video.renderJob.progress}% · {video.renderJob.currentStep}</p>{video.renderJob.error && <p className="error">{video.renderJob.error}</p>}</section>}
    {video.scriptId && <TTSControls scriptId={video.scriptId._id} onComplete={load}/>}
    <div className="studio-layout"><section className="panel timeline"><h2>Scene timeline</h2>{scenes.length === 0 ? <p className="muted">No scenes available.</p> : scenes.map((scene) => { const image = scene.assetIds?.find((asset) => asset.type === "image"); const audio = scene.assetIds?.find((asset) => asset.type === "audio"); return <div className="timeline-item" key={scene._id}><b>Scene {scene.sceneNumber}</b><small>{scene.startTime}s – {scene.endTime}s</small>{image?.storagePath && <Image unoptimized width={1080} height={1920} alt={scene.visualDescription} src={`/api/media?path=${encodeURIComponent(image.storagePath)}`}/>}<p>{scene.narration}</p>{audio?.storagePath ? <><audio controls preload="metadata" src={`/api/media?path=${encodeURIComponent(audio.storagePath)}`}/><small>{audio.provider} · {audio.metadata?.duration?.toFixed(2)}s · {audio.metadata?.sampleRate ? `${audio.metadata.sampleRate / 1000} kHz` : ""} · {audio.metadata?.voice}</small></> : <span className="badge">voice missing</span>}</div>; })}</section>
      <section className="panel preview"><h2>Preview</h2>{video.outputPath ? <video controls src={`/api/media?path=${encodeURIComponent(video.outputPath)}`} /> : <div className="video-placeholder">Generate every scene image and voice, then render.</div>}<div className="button-row"><button onClick={() => setShowSubtitles(!showSubtitles)}>{showSubtitles ? "Hide" : "Edit"} subtitles</button><button disabled={busy || !subtitles.length} onClick={() => void saveSubtitles(true)}>Generate SRT</button>{video.subtitlePath && <a className="link" href={`/api/media?path=${encodeURIComponent(video.subtitlePath)}`} target="_blank">Preview SRT</a>}</div>{showSubtitles && <div className="form subtitle-editor">{subtitles.map((entry, index) => <label key={entry.sceneId}>Scene {entry.sceneNumber} · {entry.start}s–{entry.end}s<textarea value={entry.text} onChange={(event) => setSubtitles(subtitles.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item))}/></label>)}<button className="primary" disabled={busy} onClick={() => void saveSubtitles(false)}>Save subtitles</button></div>}</section>
      <section className="panel properties"><h2>Properties</h2><p><b>Status</b><br/>{video.status}</p><p><b>Lesson</b><br/>{video.lessonId?.title || "Not linked"}</p><p><b>Script</b><br/>{video.scriptId?.title || "Not linked"}</p>{video.scriptId && <details><summary>Script</summary><p><b>{video.scriptId.hook}</b></p><p>{video.scriptId.narration}</p><p>{video.scriptId.callToAction}</p></details>}{video.status === "ready_for_review" && <div className="button-row"><button className="primary" onClick={() => void action("approve")}>Approve</button><button onClick={() => void action("reject")}>Reject</button></div>}{video.status === "approved" && <Link className="primary link-button" href={`/dashboard/videos/${videoId}/publish`}>Publish to YouTube</Link>}</section></div>
  </main>;
}
