import { NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";
import { SystemSetting } from "@/models";
import { llmConfig, ttsConfig } from "@/lib/ai/config";
import { loadImageSettings } from "@/lib/ai/image-settings";
import { providerConfigured } from "@/lib/ai/image-provider";
import { env } from "@/lib/env";
const defaults = { render: { width: 1080, height: 1920, fps: 30, subtitleMargin: 300 }, youtube: { privacyStatus: "private" } };
export async function GET() { await connectToDatabase(); const stored = await SystemSetting.findOne({ key: "application" }).lean() as unknown as { value?: typeof defaults } | null; const llm = llmConfig(), image = await loadImageSettings(), tts = ttsConfig(); return NextResponse.json({ values: stored?.value || defaults, providers: { llm: { provider: llm.provider, model: llm.model, configured: llm.provider === "mock" || Boolean(process.env.OPENAI_API_KEY) }, image: { provider: image.provider, model: image.model, configured: providerConfigured(image.provider) }, tts: { provider: tts.provider, model: tts.model, voice: tts.voice, configured: tts.provider === "mock" || tts.provider === "vieneu" || Boolean(process.env.OPENAI_API_KEY) }, youtube: { provider: process.env.YOUTUBE_PROVIDER || "mock", configured: Boolean(process.env.YOUTUBE_CLIENT_ID && process.env.YOUTUBE_CLIENT_SECRET && process.env.YOUTUBE_CREDENTIAL_KEY) } }, storage: { root: env.storageRoot }, pricing: { configured: Boolean(process.env.AI_PRICING_JSON) }, budgets: { daily: Number(process.env.DAILY_AI_BUDGET || 0), monthly: Number(process.env.MONTHLY_AI_BUDGET || 0) } }); }
export async function PUT(request: Request) { try { const input = await request.json(); const render = input?.render; const youtube = input?.youtube; if (!render || ![render.width, render.height, render.fps, render.subtitleMargin].every((value: unknown) => Number.isInteger(Number(value)) && Number(value) > 0)) return NextResponse.json({ error: "Render settings must be positive integers" }, { status: 400 }); if (!["private", "unlisted", "public"].includes(String(youtube?.privacyStatus))) return NextResponse.json({ error: "Invalid YouTube privacy" }, { status: 400 }); if (youtube.privacyStatus === "public" && input.confirmPublic !== true) return NextResponse.json({ error: "Public privacy requires explicit confirmation" }, { status: 400 }); const value = { render: { width: Number(render.width), height: Number(render.height), fps: Number(render.fps), subtitleMargin: Number(render.subtitleMargin) }, youtube: { privacyStatus: String(youtube.privacyStatus) } }; await connectToDatabase(); await SystemSetting.findOneAndUpdate({ key: "application" }, { key: "application", category: "application", value }, { upsert: true, new: true, setDefaultsOnInsert: true }); return NextResponse.json({ values: value }); } catch { return NextResponse.json({ error: "Unable to save settings" }, { status: 400 }); } }
