import { createHash, randomBytes, scrypt as nodeScrypt, timingSafeEqual } from "node:crypto"; import { promisify } from "node:util"; import { connectToDatabase } from "@/lib/mongodb"; import { Session, User } from "@/models"; import { signSession, verifySession } from "@/lib/session-token";
const scrypt = promisify(nodeScrypt); const cookieName = "edu_session"; export const authCookieName = cookieName; const tokenHash = (token: string) => createHash("sha256").update(token).digest("hex");
export async function hashPassword(password: string) { const salt = randomBytes(16); const derived = await scrypt(password, salt, 64) as Buffer; return `scrypt:${salt.toString("hex")}:${derived.toString("hex")}`; }
export async function verifyPassword(password: string, encoded: string) { const [, saltHex, hashHex] = encoded.split(":"); if (!saltHex || !hashHex || !/^[a-f0-9]+$/i.test(saltHex) || !/^[a-f0-9]+$/i.test(hashHex)) return false; try { const derived = await scrypt(password, Buffer.from(saltHex, "hex"), 64) as Buffer; const expected = Buffer.from(hashHex, "hex"); return derived.length === expected.length && timingSafeEqual(derived, expected); } catch { return false; } }
export async function createSession(userId: string) { await connectToDatabase(); const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); const token = await signSession(userId, expiresAt); await Session.create({ userId, tokenHash: tokenHash(token), expiresAt }); return { token, expiresAt }; }
export async function getSessionUser(token?: string) { if (!token || !(await verifySession(token))) return null; await connectToDatabase(); const session = await Session.findOne({ tokenHash: tokenHash(token), expiresAt: { $gt: new Date() } }).populate({ path: "userId", select: "email role status" }).lean() as unknown as { userId?: { email: string; role: string; status: string } } | null; return session?.userId?.status === "active" ? session.userId : null; }
export async function destroySession(token?: string) { if (token) { await connectToDatabase(); await Session.deleteOne({ tokenHash: tokenHash(token) }); } }
function secureCookie() { try { return new URL(process.env.APP_URL || "http://localhost").protocol === "https:"; } catch { return false; } }
export function sessionCookie(token: string, expiresAt: Date, secure = secureCookie()) { return `${cookieName}=${token}; Path=/; HttpOnly; SameSite=Lax;${secure ? " Secure;" : ""} Max-Age=${Math.max(0, Math.floor((expiresAt.getTime() - Date.now()) / 1000))}`; } export function clearSessionCookie(secure = secureCookie()) { return `${cookieName}=; Path=/; HttpOnly; SameSite=Lax;${secure ? " Secure;" : ""} Max-Age=0`; }
export async function ensureAdmin(email: string, password: string) { await connectToDatabase(); let user = await User.findOne({ email }).select("+passwordHash"); const configuredEmail = process.env.ADMIN_EMAIL; const configuredPassword = process.env.ADMIN_PASSWORD; if (!user && configuredEmail && configuredPassword && email === configuredEmail && password === configuredPassword) user = await User.create({ email, passwordHash: await hashPassword(password), role: "admin" }); return user; }
