import type { ScriptOutput } from "@/lib/ai/types";
import { readFile } from "node:fs/promises";
import { decryptCredential } from "@/lib/credentials";
export type YouTubeMetadata = { title: string; description: string; tags: string[]; hashtags: string[] };
export function generateYouTubeMetadata(input: { lessonTitle: string; subject?: string; grade?: string; script?: Partial<ScriptOutput> }): YouTubeMetadata { const title = `${input.lessonTitle}${input.subject ? ` | ${input.subject}` : ""}${input.grade ? ` lớp ${input.grade}` : ""}`; const tags = [input.lessonTitle, input.subject, input.grade ? `lớp ${input.grade}` : undefined, "giáo dục", "học nhanh"].filter((item): item is string => Boolean(item)); return { title: title.slice(0, 95), description: `${input.script?.educationalGoal || `Cùng học ${input.lessonTitle}`}\n\nVideo giáo dục ngắn gọn, dễ hiểu dành cho học sinh.`, tags, hashtags: tags.slice(0, 4).map((tag) => `#${tag.replace(/\s+/g, "")}`) }; }
export interface YouTubeProvider { name: string; upload(videoPath: string, metadata: YouTubeMetadata, privacyStatus: string): Promise<{ published: boolean; message: string; youtubeVideoId?: string }>; }
export class MockYouTubeProvider implements YouTubeProvider { name = "mock-local"; async upload(videoPath: string, metadata: YouTubeMetadata, privacyStatus: string) { void videoPath; void metadata; void privacyStatus; return { published: false, message: "Mock mode: no YouTube upload was performed." }; } }
export class RealYouTubeProvider implements YouTubeProvider { name = "youtube"; constructor(private readonly accessToken: string, private readonly refreshToken?: string) {} async upload(videoPath: string, metadata: YouTubeMetadata, privacyStatus: string) { void this.refreshToken; const file = await readFile(videoPath); const body = new FormData(); body.append("metadata", new Blob([JSON.stringify({ snippet: { title: metadata.title, description: `${metadata.description}\n\n${metadata.hashtags.join(" ")}`, tags: metadata.tags, categoryId: "27" }, status: { privacyStatus: privacyStatus || "private" } })], { type: "application/json" })); body.append("video", new Blob([file], { type: "video/mp4" }), "video.mp4"); const response = await fetch("https://www.googleapis.com/upload/youtube/v3/videos?part=snippet,status&uploadType=multipart", { method: "POST", headers: { Authorization: `Bearer ${this.accessToken}` }, body }); if (response.status === 401) throw new Error("YouTube authentication_required"); if (response.status === 403) { const message = await response.text(); if (/quota/i.test(message)) throw new Error("YouTube quota_exceeded"); throw new Error("YouTube permission denied"); } if (response.status === 429 || response.status >= 500) throw new Error(`YouTube retryable error (${response.status})`); if (!response.ok) throw new Error(`YouTube upload failed (${response.status})`); const result = await response.json() as { id?: string }; return { published: true, youtubeVideoId: result.id, message: "Video uploaded to YouTube" }; } }
export function realYouTubeProvider(accessToken: string, refreshToken?: string) { return new RealYouTubeProvider(decryptCredential(accessToken), refreshToken ? decryptCredential(refreshToken) : undefined); }
