import { createHash, randomUUID } from "node:crypto";
import OpenAI from "openai";
import sharp from "sharp";
import { contentHash } from "@/lib/ai/cache";
import { IMAGE_MODEL_DEFAULTS, type ImageProviderId, envImageModel, envImageProvider, validateImageModel, validateImageProviderId } from "@/lib/ai/image-settings";
import { validateAssetUpload, validateUploadContent } from "@/lib/upload-validation";

export type ImageRequest = { prompt: string; aspectRatio?: string; negativePrompt?: string; style?: string; character?: string; type?: string; dimensions?: { width: number; height: number }; settings?: Record<string, unknown> };
export type ImageUsage = { imageCount: number; inputTokens?: number; outputTokens?: number };
export type ImageResult = { provider: string; providerId: ImageProviderId; model: string; status: "mock" | "generated" | "not_configured"; data: Buffer; mimeType: "image/png" | "image/jpeg" | "image/webp"; width: number; height: number; size: number; hash: string; message: string; cached?: boolean; requestId?: string; usage?: ImageUsage; storagePath?: string };
export interface ImageProvider { name: string; providerId: ImageProviderId; displayName: string; model: string; generateImage(request: ImageRequest): Promise<ImageResult>; }
export type ImageProviderErrorCode = "CONFIGURATION_ERROR" | "AUTHENTICATION_ERROR" | "QUOTA_EXCEEDED" | "RATE_LIMITED" | "BUDGET_EXCEEDED" | "INVALID_REQUEST" | "PROVIDER_ERROR" | "INVALID_IMAGE" | "NETWORK_ERROR";

export class ImageProviderError extends Error {
  constructor(public code: ImageProviderErrorCode, message: string, public httpStatus = 502, public retryable = false, public requestId?: string, public retryAfterMs?: number) { super(message); this.name = "ImageProviderError"; }
}
export function imageCacheKey(provider: string, model: string, request: ImageRequest) { return contentHash({ provider, model, request }); }
const xmlEscape = (value: string) => value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[character] || character);
const getHeader = (headers: unknown, name: string) => typeof (headers as { get?: unknown })?.get === "function" ? (headers as { get(name: string): string | null }).get(name) : undefined;
const errorField = (error: unknown, key: string) => { if (!error || typeof error !== "object") return undefined; const direct = (error as Record<string, unknown>)[key]; const nested = (error as { error?: Record<string, unknown> }).error?.[key]; return typeof direct === "string" || typeof direct === "number" ? direct : typeof nested === "string" || typeof nested === "number" ? nested : undefined; };
const retryAfter = (error: unknown) => { const headers = error && typeof error === "object" ? (error as { headers?: unknown }).headers : undefined; const ms = getHeader(headers, "retry-after-ms"); if (ms && /^\d+(\.\d+)?$/.test(ms)) return Number(ms); const value = getHeader(headers, "retry-after"); if (!value) return undefined; const parsed = /^\d+(\.\d+)?$/.test(value) ? Number(value) * 1000 : Date.parse(value) - Date.now(); return Number.isFinite(parsed) ? Math.max(0, parsed) : undefined; };

export function classifyImageProviderError(error: unknown, provider = "Image provider"): ImageProviderError {
  if (error instanceof ImageProviderError) return error;
  const status = Number(errorField(error, "status") || 0), code = String(errorField(error, "code") || "").toLowerCase(), type = String(errorField(error, "type") || "").toLowerCase();
  const raw = String(errorField(error, "message") || (error instanceof Error ? error.message : "")).toLowerCase();
  const headers = error && typeof error === "object" ? (error as { headers?: unknown }).headers : undefined;
  const requestId = String(errorField(error, "request_id") || getHeader(headers, "x-request-id") || getHeader(headers, "x-request-id") || "") || undefined;
  if (status === 401 || status === 403) return new ImageProviderError("AUTHENTICATION_ERROR", `${provider} authentication or model access failed. Check the protected server credential and permissions.`, 503, false, requestId);
  if (status === 429 && (code.includes("quota") || code.includes("credit") || type.includes("quota") || /credit|quota|billing|spend|usage limit/.test(raw))) return new ImageProviderError("QUOTA_EXCEEDED", `${provider} quota or billing limit was reached. Check provider billing and quotas.`, 503, false, requestId);
  if (status === 429) return new ImageProviderError("RATE_LIMITED", `${provider} is temporarily rate limited. Try again shortly.`, 429, true, requestId, retryAfter(error));
  if ([400,404,409,422].includes(status)) return new ImageProviderError("INVALID_REQUEST", `${provider} rejected the model, prompt, or image settings.`, 400, false, requestId);
  if (status >= 500 || status === 408) return new ImageProviderError("PROVIDER_ERROR", `${provider} is temporarily unavailable.`, 503, true, requestId, retryAfter(error));
  if (error instanceof OpenAI.APIConnectionError || /abort|timeout|network|fetch failed|connection/.test(raw)) return new ImageProviderError("NETWORK_ERROR", `Could not connect to ${provider}.`, 502, true, requestId);
  return new ImageProviderError("PROVIDER_ERROR", `${provider} image generation failed.`, 502, false, requestId);
}
function detectRasterMime(data: Buffer): { mimeType: "image/png" | "image/jpeg" | "image/webp"; extension: "png" | "jpg" | "webp" } {
  if (data.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]))) return { mimeType: "image/png", extension: "png" };
  if (data.length > 3 && data[0] === 0xff && data[1] === 0xd8 && data[2] === 0xff) return { mimeType: "image/jpeg", extension: "jpg" };
  if (data.length >= 12 && data.subarray(0,4).toString() === "RIFF" && data.subarray(8,12).toString() === "WEBP") return { mimeType: "image/webp", extension: "webp" };
  throw new ImageProviderError("INVALID_IMAGE", "Provider returned unsupported image bytes.", 502);
}
export async function validateGeneratedRaster(data: Buffer, declaredMime?: string) {
  if (!Buffer.isBuffer(data) || !data.length || data.length > Number(process.env.MAX_IMAGE_ASSET_SIZE || 20 * 1024 * 1024)) throw new ImageProviderError("INVALID_IMAGE", "Provider returned an empty or oversized image.", 502);
  const detected = detectRasterMime(data); if (declaredMime && declaredMime.split(";")[0].trim() !== detected.mimeType) throw new ImageProviderError("INVALID_IMAGE", "Provider image Content-Type does not match its bytes.", 502);
  try { validateAssetUpload(`generated.${detected.extension}`, detected.mimeType, data, "image"); validateUploadContent(`generated.${detected.extension}`, detected.mimeType, data); const metadata = await sharp(data, { failOn: "error" }).metadata(); if (metadata.pages && metadata.pages !== 1) throw new Error(); const width = metadata.width || 0, height = metadata.height || 0; if (width < 1 || height < 1 || width > 12000 || height > 12000) throw new Error(); return { ...detected, width, height, size: data.length, hash: createHash("sha256").update(data).digest("hex") }; } catch (error) { if (error instanceof ImageProviderError) throw error; throw new ImageProviderError("INVALID_IMAGE", "Provider image failed integrity or dimension validation.", 502); }
}
function normalizeRequest(request: ImageRequest) { const prompt = String(request.prompt || "").replace(/\s+/g, " ").trim(); if (!prompt || prompt.length > 12000) throw new ImageProviderError("INVALID_REQUEST", "Image prompt must be between 1 and 12,000 characters.", 400); return { ...request, prompt }; }
async function normalizedResult(providerId: ImageProviderId, model: string, data: Buffer, message: string, requestId?: string, declaredMime?: string, status: "mock" | "generated" = "generated"): Promise<ImageResult> { const valid = await validateGeneratedRaster(data, declaredMime); return { provider: providerId, providerId, model, status, data, ...valid, message, cached: false, requestId: requestId || randomUUID(), usage: { imageCount: status === "mock" ? 0 : 1 } }; }

export class MockImageProvider implements ImageProvider {
  name = "mock"; providerId = "mock" as const; displayName = "Mock (local)";
  constructor(public model = IMAGE_MODEL_DEFAULTS.mock) {}
  async generateImage(raw: ImageRequest) { const request = normalizeRequest(raw); const width = request.dimensions?.width || 1080, height = request.dimensions?.height || 1920; const label = xmlEscape(request.prompt.slice(0,180)); const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="#e8f6ef"/><text x="50%" y="18%" text-anchor="middle" font-size="54" font-family="sans-serif" fill="#0e9b62">MOCK ASSET</text><text x="50%" y="55%" text-anchor="middle" font-size="32" font-family="sans-serif" fill="#17251f">${label}</text></svg>`; const data = await sharp(Buffer.from(svg)).png().toBuffer(); return normalizedResult(this.providerId, this.model, data, "Mock image generated", undefined, "image/png", "mock"); }
}
type OpenAITransport = (request: { model: string; prompt: string; size: "1024x1536"; output_format: "png"; n: 1 }) => Promise<{ encoded?: string; requestId?: string }>;
export type OpenAIImageProviderOptions = { transport?: OpenAITransport; sleep?: (milliseconds: number) => Promise<void>; random?: () => number; imageStorage?: unknown };
export class OpenAIImageProvider implements ImageProvider {
  name = "openai"; providerId = "openai" as const; displayName = "OpenAI";
  constructor(public model = envImageModel("openai"), private options: OpenAIImageProviderOptions = {}) { if (typeof model === "object") { this.options = model as OpenAIImageProviderOptions; this.model = envImageModel("openai"); } this.model = validateImageModel(this.model); }
  private transport(): OpenAITransport { if (this.options.transport) return this.options.transport; const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY, baseURL: process.env.OPENAI_BASE_URL || undefined, organization: process.env.OPENAI_ORG_ID || process.env.OPENAI_ORGANIZATION || undefined, project: process.env.OPENAI_PROJECT_ID || undefined, timeout: Math.min(120000, Number(process.env.AI_TIMEOUT_MS || 60000)), maxRetries: 0 }); return async request => { const { data, response } = await client.images.generate(request).withResponse(); return { encoded: data.data?.[0]?.b64_json, requestId: response.headers.get("x-request-id") || undefined }; }; }
  async generateImage(raw: ImageRequest) { if (!process.env.OPENAI_API_KEY?.trim()) throw new ImageProviderError("CONFIGURATION_ERROR", "OpenAI is selected but OPENAI_API_KEY is not configured on the server.", 503); const request = normalizeRequest(raw); const transport = this.transport(), sleep = this.options.sleep || (ms => new Promise(resolve => setTimeout(resolve, ms))), random = this.options.random || Math.random; const max = Math.min(3, Math.max(1, Number(process.env.AI_IMAGE_MAX_ATTEMPTS || 3))), base = Math.max(0, Number(process.env.AI_RETRY_BASE_MS || 1000)); let last: ImageProviderError | undefined;
    for (let attempt=0; attempt<max; attempt++) try { const response = await transport({ model: this.model, prompt: [request.prompt, request.negativePrompt].filter(Boolean).join("\nAvoid: "), size: "1024x1536", output_format: "png", n: 1 }); if (!response.encoded) throw new ImageProviderError("INVALID_IMAGE", "OpenAI returned no image data.", 502, false, response.requestId); return await normalizedResult(this.providerId, this.model, Buffer.from(response.encoded, "base64"), "OpenAI image generated", response.requestId, "image/png"); } catch (error) { const safe = classifyImageProviderError(error, "OpenAI"); last = safe; if (!safe.retryable || attempt + 1 >= max) throw safe; const delay = safe.retryAfterMs ?? Math.round(Math.min(30000, base * 2 ** attempt) * (0.5 + random() * 0.5)); if (delay > 60000) throw safe; await sleep(delay); }
    throw last || new ImageProviderError("PROVIDER_ERROR", "OpenAI image generation failed."); }
}
export type FetchLike = typeof fetch;
export class HuggingFaceImageProvider implements ImageProvider { name = "huggingface"; providerId = "huggingface" as const; displayName = "Hugging Face"; constructor(public model = envImageModel("huggingface"), private fetcher: FetchLike = fetch) { this.model = validateImageModel(model); }
  async generateImage(raw: ImageRequest) { if (!process.env.HF_TOKEN?.trim()) throw new ImageProviderError("CONFIGURATION_ERROR", "Hugging Face is selected but HF_TOKEN is not configured on the server.", 503); const request = normalizeRequest(raw); try { const response = await this.fetcher(`https://router.huggingface.co/hf-inference/models/${encodeURIComponent(this.model)}`, { method: "POST", headers: { Authorization: `Bearer ${process.env.HF_TOKEN}`, "Content-Type": "application/json", Accept: "image/png,image/jpeg,image/webp" }, body: JSON.stringify({ inputs: request.prompt, parameters: request.negativePrompt ? { negative_prompt: request.negativePrompt } : undefined }) }); if (!response.ok) throw { status: response.status, headers: response.headers }; const data = Buffer.from(await response.arrayBuffer()); return normalizedResult(this.providerId, this.model, data, "Hugging Face image generated", response.headers.get("x-request-id") || undefined, response.headers.get("content-type") || undefined); } catch (error) { throw classifyImageProviderError(error, "Hugging Face"); } }
}
export class GeminiImageProvider implements ImageProvider { name = "gemini"; providerId = "gemini" as const; displayName = "Google Gemini"; constructor(public model = envImageModel("gemini"), private fetcher: FetchLike = fetch) { this.model = validateImageModel(model); }
  async generateImage(raw: ImageRequest) { if (!process.env.GEMINI_API_KEY?.trim() || !this.model) throw new ImageProviderError("CONFIGURATION_ERROR", "Gemini is selected but GEMINI_API_KEY and a supported image model are not configured on the server.", 503); const request = normalizeRequest(raw); try { const response = await this.fetcher(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(this.model)}:generateContent`, { method: "POST", headers: { "x-goog-api-key": process.env.GEMINI_API_KEY, "Content-Type": "application/json" }, body: JSON.stringify({ contents: [{ parts: [{ text: request.prompt }] }], generationConfig: { responseModalities: ["IMAGE"] } }) }); if (!response.ok) throw { status: response.status, headers: response.headers }; const json = await response.json() as { candidates?: Array<{ content?: { parts?: Array<{ inlineData?: { data?: string; mimeType?: string } }> } }> }; const image = json.candidates?.flatMap(item => item.content?.parts || []).find(part => part.inlineData?.data)?.inlineData; if (!image?.data) throw new ImageProviderError("INVALID_IMAGE", "Gemini returned no image data.", 502); return normalizedResult(this.providerId, this.model, Buffer.from(image.data, "base64"), "Gemini image generated", response.headers.get("x-request-id") || undefined, image.mimeType); } catch (error) { throw classifyImageProviderError(error, "Gemini"); } }
}
export const IMAGE_PROVIDER_REGISTRY = {
  mock: { providerId: "mock", displayName: "Mock (local)", defaultModel: IMAGE_MODEL_DEFAULTS.mock }, openai: { providerId: "openai", displayName: "OpenAI", defaultModel: IMAGE_MODEL_DEFAULTS.openai }, huggingface: { providerId: "huggingface", displayName: "Hugging Face", defaultModel: IMAGE_MODEL_DEFAULTS.huggingface }, gemini: { providerId: "gemini", displayName: "Google Gemini", defaultModel: IMAGE_MODEL_DEFAULTS.gemini },
} as const;
export function createImageProvider(provider: string = envImageProvider(), model?: string): ImageProvider { const id = validateImageProviderId(provider); const resolved = validateImageModel(model || envImageModel(id)); if (id === "mock") return new MockImageProvider(resolved); if (id === "openai") return new OpenAIImageProvider(resolved); if (id === "huggingface") return new HuggingFaceImageProvider(resolved); return new GeminiImageProvider(resolved); }
export function providerConfigured(id: ImageProviderId) { return id === "mock" || id === "openai" ? id === "mock" || Boolean(process.env.OPENAI_API_KEY?.trim()) : id === "huggingface" ? Boolean(process.env.HF_TOKEN?.trim()) : Boolean(process.env.GEMINI_API_KEY?.trim()); }
export function availableImageProviders() { return Object.values(IMAGE_PROVIDER_REGISTRY).map(item => ({ ...item, configured: providerConfigured(item.providerId) })); }
export function imageProviderStatus(provider: ImageProviderId = envImageProvider(), model = envImageModel(provider)) { const configured = providerConfigured(provider), info = IMAGE_PROVIDER_REGISTRY[provider]; return { provider, providerId: provider, displayName: info.displayName, model, configured, mode: provider === "mock" ? "mock" : configured ? "real" : "not_configured", label: info.displayName, message: configured ? `${info.displayName} / ${model}` : `${info.displayName} is selected but its server credential is not configured.` }; }
/** Legacy env-resolved instance; request-time services must use loadImageSettings + factory instead. */
export const imageProvider: ImageProvider = createImageProvider();
