import type { LessonAnalysisOutput, ScriptOutput, ScriptReviewOutput, StoryboardSceneOutput, YouTubeMetadataOutput } from "@/lib/ai/types";
const isObject = (value: unknown): value is Record<string, unknown> => Boolean(value && typeof value === "object" && !Array.isArray(value));
const exactKeys = (value: Record<string, unknown>, keys: string[]) => { const actual = Object.keys(value).sort(); const expected = [...keys].sort(); return actual.length === expected.length && actual.every((key, index) => key === expected[index]); };
const strings = (value: unknown, allowEmpty = true): value is string[] => Array.isArray(value) && value.every((item) => typeof item === "string" && (allowEmpty || item.trim().length > 0));
export function validAnalysis(value: unknown): value is LessonAnalysisOutput { if (!isObject(value) || !exactKeys(value, ["sourceSummary", "learningObjectives", "keyFacts", "definitions", "formulas", "examples", "commonMistakes", "keywords", "difficulty"])) return false; return typeof value.sourceSummary === "string" && value.sourceSummary.trim().length > 0 && strings(value.learningObjectives, false) && value.learningObjectives.length > 0 && strings(value.keyFacts, false) && value.keyFacts.length > 0 && strings(value.definitions) && strings(value.formulas) && strings(value.examples) && strings(value.commonMistakes) && strings(value.keywords, false) && ["beginner", "intermediate", "advanced"].includes(String(value.difficulty)); }
export function validScript(value: unknown): value is ScriptOutput { if (!isObject(value) || !exactKeys(value, ["title", "hook", "narration", "targetAudience", "educationalGoal", "callToAction"])) return false; return [value.title, value.hook, value.narration, value.targetAudience, value.educationalGoal, value.callToAction].every((item) => typeof item === "string" && item.trim().length > 0); }
export function validScriptReview(value: unknown): value is ScriptReviewOutput { return isObject(value) && exactKeys(value, ["valid", "errors", "warnings"]) && typeof value.valid === "boolean" && strings(value.errors) && strings(value.warnings); }
export function validStoryboard(value: unknown): value is StoryboardSceneOutput[] { return Array.isArray(value) && value.length >= 5 && value.length <= 7 && value.every((scene) => isObject(scene) && exactKeys(scene, ["sceneNumber", "startTime", "endTime", "duration", "narration", "visualDescription", "imagePrompt", "subtitleText"]) && [scene.sceneNumber, scene.startTime, scene.endTime, scene.duration].every((item) => typeof item === "number" && Number.isFinite(item)) && [scene.narration, scene.visualDescription, scene.imagePrompt, scene.subtitleText].every((item) => typeof item === "string" && item.trim().length > 0)); }
export function validMetadata(value: unknown): value is YouTubeMetadataOutput { return isObject(value) && exactKeys(value, ["title", "description", "tags", "hashtags"]) && typeof value.title === "string" && value.title.trim().length > 0 && value.title.length <= 100 && typeof value.description === "string" && value.description.trim().length > 0 && strings(value.tags, false) && strings(value.hashtags, false); }
export function parseStructured<T>(value: unknown, guard: (value: unknown) => value is T): T { if (typeof value !== "string") { if (guard(value)) return value; throw new Error("Invalid structured AI output"); } if (!value.trim()) throw new Error("AI output was empty"); let parsed: unknown; try { parsed = JSON.parse(value); } catch { throw new Error("AI output was not valid JSON"); } if (!guard(parsed)) throw new Error("AI output failed schema validation"); return parsed; }
