import { VieNeuTTSProvider } from "@/lib/ai/vieneu-provider";
import { storage } from "@/lib/storage"; import { contentHash } from "@/lib/ai/cache"; import { ttsConfig } from "@/lib/ai/config";
export type TTSRequest = { narration: string; voice: string; model: string; language: string; speed?: number; referenceAudio?: string; referenceText?: string; referenceAudioHash?: string; force?: boolean }; export type TTSResult = { provider: string; status: "generated" | "mock" | "not_configured"; storagePath?: string; duration?: number; audioSeconds?: number; sampleRate?: number; channels?: number; codec?: string; fileSize?: number; inferenceMs?: number; rtf?: number; peakRssMB?: number; estimatedCost: number; cached: boolean; message: string };
export interface TTSProvider { name: string; synthesize(request: TTSRequest): Promise<TTSResult>; }
export function ttsCacheKey(provider: string, request: TTSRequest) { return contentHash({ provider, request }); }
function mockWav(seconds: number) { const rate = 16000; const samples = Math.max(1, Math.round(rate * seconds)); const dataSize = samples * 2; const buffer = Buffer.alloc(44 + dataSize); buffer.write("RIFF", 0); buffer.writeUInt32LE(36 + dataSize, 4); buffer.write("WAVEfmt ", 8); buffer.writeUInt32LE(16, 16); buffer.writeUInt16LE(1, 20); buffer.writeUInt16LE(1, 22); buffer.writeUInt32LE(rate, 24); buffer.writeUInt32LE(rate * 2, 28); buffer.writeUInt16LE(2, 32); buffer.writeUInt16LE(16, 34); buffer.write("data", 36); buffer.writeUInt32LE(dataSize, 40); for (let index = 0; index < samples; index += 1) buffer.writeInt16LE(Math.round(Math.sin(2 * Math.PI * 220 * index / rate) * 900), 44 + index * 2); return buffer; }
export class MockTTSProvider implements TTSProvider { name = "mock-local"; async synthesize(request: TTSRequest) { const hash = ttsCacheKey(this.name, request); const filename = `${hash}.wav`; const duration = Number(Math.max(1, request.narration.trim().split(/\s+/).length / 2.85).toFixed(1)); const cached = await storage.exists("audio", filename); if (!cached) await storage.save("audio", filename, mockWav(duration)); return { provider: this.name, status: "mock" as const, storagePath: `audio/${filename}`, duration, audioSeconds: duration, estimatedCost: 0, cached, message: cached ? "MOCK voice reused" : "MOCK voice generated" }; } }
export class OpenAITTSProvider implements TTSProvider { name = "openai-tts"; async synthesize(request: TTSRequest) { const key = process.env.OPENAI_API_KEY; if (!key) return { provider: this.name, status: "not_configured" as const, estimatedCost: 0, cached: false, message: "TTS provider not configured" }; const hash = contentHash({ provider: this.name, request }); const filename = `${hash}.mp3`; if (await storage.exists("audio", filename)) return { provider: this.name, status: "generated" as const, storagePath: `audio/${filename}`, estimatedCost: 0, cached: true, message: "Reused cached audio" }; const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), Number(process.env.AI_TIMEOUT_MS || 30000)); try { const response = await fetch(`${process.env.OPENAI_BASE_URL || "https://api.openai.com/v1"}/audio/speech`, { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: request.model, voice: request.voice, input: request.narration, response_format: "mp3" }), signal: controller.signal }); if (!response.ok) throw new Error(`TTS request failed (${response.status})`); await storage.save("audio", filename, Buffer.from(await response.arrayBuffer())); const duration = Number((request.narration.split(/\s+/).length / 2.85).toFixed(1)); return { provider: this.name, status: "generated" as const, storagePath: `audio/${filename}`, duration, audioSeconds: duration, estimatedCost: 0, cached: false, message: "Audio generated" }; } finally { clearTimeout(timer); } } }
export function createTTSProvider(provider = ttsConfig().provider): TTSProvider {
  if (provider === "vieneu") return new VieNeuTTSProvider();
  if (provider === "openai") return new OpenAITTSProvider();
  if (provider === "mock") return new MockTTSProvider();
  throw new Error("TTS_CONFIGURATION: unsupported provider");
}
export const ttsProvider: TTSProvider = createTTSProvider();
